### ISSUE TITLE
How to configure Kafka in Docker to avoid PolicyViolationException for delete records

### ISSUE THREAD

**Issue by zcaudate** [bitnami/bitnami-docker-kafka#105]
I've asked the question on [stackoverflow](https://stackoverflow.com/questions/62115888/how-to-configure-kafka-in-docker-to-avoid-policyviolationexception-for-delete-re) but thought it might be better to ask here as well.

I've set `KAFKA_CFG_DELETE_TOPIC_ENABLE` to true but am getting a PolicyViolationException when using 

```
kafka-delete-records --bootstrap-server localhost:9092 --offset-json-file tmp16523977715454317626.json
```

Is there another way to get this working?

**Comment by miguelaeh** [comment]
Hi @zcaudate ,
Checking you StackOverflow thread I saw that you are using the version `2.3.1`. Is the error happening on the `2.5.0` too?

**Comment by zcaudate** [comment]
@miguelaeh, I just noticed your reply. Let me check and get back to you.
