### ISSUE TITLE
Topic disappears after zookeeper restart

### ISSUE THREAD

**Issue by Graeme-B** [bitnami/bitnami-docker-kafka#106]
I have a simple application with one zookeeper docker container and one broker docker container. I've added volume management to each with the parameter -v /kafka:/bitnami/kafka. I can create topics and run producers and consumers. However, when I stop and restart zookeeper and the broker, the topics I have created disappear. I can still see the topic subdirectory in the folder /kafka/data, but this seems to be recreated on startup. Am I missing a config flag which will stop this happening? Many thanks.

**Comment by joancafom** [comment]
Hi @Graeme-B ,

Glad to help you 😁 Could you provide me with your `docker-compose.yml` as well as the steps you follow so that I can check it for you? May it contain sensitive data (such us passwords), you can mask them using `****`. 

Thanks!

**Comment by Graeme-B** [comment]
Hi @joancafom - thanks for your help. I'm not using docker-compose: I'm currently running from the bitnami docker containers. The plan is to move to one of docker-swarm, kubernetes or openshift at some point, but I'm starting with plain docker.

I start zookeeper with
```
#!/bin/bash
docker run -d \
  --name zookeeper-server \
  --network app-tier \
  -p 2181:2181 \
  -e ALLOW_ANONYMOUS_LOGIN=yes \
  -e ZOO_4LW_COMMANDS_WHITELIST=* \
  -v /kafka:/bitnami/kafka \
  bitnami/zookeeper:latest
```
and I start the broker with
```
#!/bin/bash
docker run -d \
  --name kafka-server \
  --network app-tier \
  -p 9092:9092 \
  -v /kafka:/bitnami/kafka \
  -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181 \
  -e ALLOW_PLAINTEXT_LISTENER=yes \
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT \
  -e KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092 \
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092 \
  -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_CFG_BROKER_ID=1 \
  bitnami/kafka:latest
```
I can create topics quite happily, using the topics.sh script, but when I stop and restart Zookeeper and the broker, the topics disappear.

I also have problems with a changing cluster IDs - when I restart the broker, it complains about a mismatched cluster.id, and I have to edit the meta.properties file to change the cluster.id. I don't know if this is relevant.

Many thanks!

**Comment by joancafom** [comment]
Hi @Graeme-B !

I have tried to replicate your issue but I did not stumbled upon your problem. How are you stopping/re-starting the containers? Also, I don't really know if it is really a good idea for both containers to share the same volume. In any case, I will try to indicate my steps here just in case we are doing something different:

0. I have created two local directories to use them as volumes in the two containers
```console
$ ls
kafka zookeeper
```
1. Create the `zookeeper-server` container:
```console
docker run -d \
  --name zookeeper-server \
  --network app-tier \
  -p 2181:2181 \
  -e ALLOW_ANONYMOUS_LOGIN=yes \
  -e ZOO_4LW_COMMANDS_WHITELIST=* \
  -v $(pwd)/zookeeper:/bitnami/kafka \
  bitnami/zookeeper:latest
```

1. Create the `kafka-server`container:
```console
$ docker run -d \
  --name kafka-server \
  --network app-tier \
  -p 9092:9092 \
  -v $(pwd)/kafka:/bitnami/kafka \
  -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181 \
  -e ALLOW_PLAINTEXT_LISTENER=yes \
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT \
  -e KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092 \
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092 \
  -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  bitnami/kafka:latest
```

2. Check both containers are running:
```console
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
b9bb155d7cf1        bitnami/kafka:latest       "/opt/bitnami/script…"   3 seconds ago       Up 1 second         0.0.0.0:9092->9092/tcp                                 kafka-server
9bec56507abc        bitnami/zookeeper:latest   "/opt/bitnami/script…"   18 seconds ago      Up 17 seconds       2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp   zookeeper-server
```

3. Create a test `topic`:
```console
$ docker run -it --rm \
 --network app-tier \
-e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181 \
bitnami/kafka:latest kafka-topics.sh --create --replication-factor 1 --partitions 1 --topic test --zookeeper zookeeper-server:2181

 10:42:26.32
 10:42:26.32 Welcome to the Bitnami kafka container
 10:42:26.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 10:42:26.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 10:42:26.32

Created topic test.

```

4. Stop & Start the containers
```console
$ docker stop kafka-server && docker stop zookeeper-server
kafka-server
zookeeper-server
$ docker start zookeeper-server && docker start kafka-server
zookeeper-server
kafka-server
```

5. Check for topics
```console
$ docker run -it --rm \
 --network app-tier \
-e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181 \
bitnami/kafka:latest kafka-topics.sh --list --zookeeper zookeeper-server:2181

 10:45:06.84
 10:45:06.84 Welcome to the Bitnami kafka container
 10:45:06.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 10:45:06.85 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 10:45:06.85

test
```

Hope it helps, thanks!

**Comment by Graeme-B** [comment]
Hi @joancafom - I haven't been able to try this yet. I will do so at the weekend. Many thanks for your help!

**Comment by Graeme-B** [comment]
Hi @joancafom - I have tried the instructions you provided and that all works fine: the topics are preserved between runs.

However, I have uncovered what I think may be causing the problem and I'd like your views on this.

I have been stopping and removing the Zookeeper and Kafka containers between runs, and recreating the containers, whereas your commands stop and restart the same container. So where you have

```docker stop kafka-server && docker stop zookeeper-server
docker start zookeeper-server && docker start kafka-server```

I have

```docker stop kafka-server
docker stop zookeeper-server
docker container rm <kafka-container-id> <zookeeper-container-id>
docker run etc etc etc```

 I have found (as I mentioned earlier) that when I do this, on starting the Kafka container I get the message


```kafka.common.InconsistentClusterIdException: The Cluster ID kioU7vZNQqa_c2lJtxh3Ow doesn't match stored clusterId Some(cR7-i4TgR8yHZRYD1WnzfQ) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
```

I can sort the problem out by editing the file kafka/data/meta.properties, and changing the cluster ID to be the one which Kafka expectes: however, when I do this, I lose the topic data.

If I leave the meta.properties file untouched and restart the Kafka container, it will sometimes start with the correct cluster ID, and if this happens then the topics are still present.

I assume that the cluster ID is the key to this problem. If I am correct, is there any way I can specify the cluster ID when starting Kafka?

Many thanks,

Graeme

**Comment by joancafom** [comment]
Hi again @Graeme-B ,

I have been able to reproduce your issue, I will investigate in the matter and let you know when I have some results.

Thanks!

**Comment by Graeme-B** [comment]
Many thanks, @joancafom - if there's anything I can do to help, please let me know.

**Comment by joancafom** [comment]
Hi @Graeme-B ,

I have further investigated the issue and spotted what it seems to be the error that is leading to this malfunction. The problem does not seem to be the applications themselves but the commands we are using to run them! When running zookeeper (and according to the [documentation](https://github.com/bitnami/bitnami-docker-zookeeper#persisting-your-data)) the path that should be used for persistence is`/bitnami/zookeeper`, Here, we have used incorrect paths that lead to data (and Clusted ID loss) every time this container is removed:

> 1. Create the `zookeeper-server` container:
> ```console
> docker run -d \
>   --name zookeeper-server \
>   --network app-tier \
>   -p 2181:2181 \
>   -e ALLOW_ANONYMOUS_LOGIN=yes \
>   -e ZOO_4LW_COMMANDS_WHITELIST=* \
>   -v $(pwd)/zookeeper:/bitnami/kafka \
>   bitnami/zookeeper:latest
> ```

Using the same command with the right directory (` -v $(pwd)/zookeeper:/bitnami/zookeeper`):
```console
$ docker run -d \
  --name zookeeper-server \
  --network app-tier \
  -p 2181:2181 \
  -e ALLOW_ANONYMOUS_LOGIN=yes \
  -e ZOO_4LW_COMMANDS_WHITELIST=* \
  -v $(pwd)/zookeeper:/bitnami/zookeeper \
  bitnami/zookeeper:latest
```

Makes the cluster not to lose its ID and all seems working flawlessly. Can you confirm that this works?

Glad to help you, thanks!

**Comment by Graeme-B** [comment]
Thank you, @joancafom - I'l try that this evening and let you know how I get on.

**Comment by Graeme-B** [comment]
@joancafom I have tried the updated zookeeper command and it works perfectly: the topics persist between stops and starts. Thank you - your help is very much appreciated.

**Comment by joancafom** [comment]
My pleasure @Graeme-B ! Do not hesitate to reach out to us at any moment if you have any further issues 😄
