### ISSUE TITLE
[Feature request] Support tls connection for zookeeper

### ISSUE THREAD

**Issue by yanjunli76** [bitnami/bitnami-docker-kafka#114]
Hi there,

This is a feature request. 

Since [bitnami-docker-zookeeper](https://github.com/bitnami/bitnami-docker-zookeeper) is support tls connection, can we update kafka image to support tls connection for zookeeper client? Thanks!

**Comment by andresbono** [comment]
Hi @yanjunli76, thanks for showing interests on this container! The feature that you mention sounds interesting. You can see that the kafka-zookeeper connections are automated but not with TLS:

https://github.com/bitnami/bitnami-docker-kafka/blob/daae7623a810f1f617d6b6a4e5d6ad25c536a975/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L320-L326

Would you like to start drafting a PR addressing the changes? Contributions are more than welcome!
