### ISSUE TITLE
Add environment variable to override listener.security.protocol.map default

### ISSUE THREAD

**Issue by priithaamer** [bitnami/bitnami-docker-kafka#12]
Hi, it seems that `listener.security.protocol.map` cannot be set in any way. Use case: set up kafka cluster with docker and connect to this cluster from the host machine for testing.

**Comment by juan131** [comment]
Hi @priithaamer  as mentioned in the [Security section](https://github.com/bitnami/bitnami-docker-kafka#security) you can use the env. variables **KAFKA_LISTENERS**, **KAFKA_ADVERTISED_LISTENERS** and **ALLOW_PLAINTEXT_LISTENER**  to configure the authentication mechanism for listeners.

For instance, if you set `ALLOW_PLAINTEXT_LISTENER=yes`:

```
############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
listeners=PLAINTEXT://:9092
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
#listeners=PLAINTEXT://:9092

# Hostname and port the broker will advertise to producers and consumers. If not set,
# it uses the value for "listeners" if configured.  Otherwise, it will use the value
# returned from java.net.InetAddress.getCanonicalHostName().
advertised.listeners=PLAINTEXT://:9092

# Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
```

If you set: `KAFKA_LISTENERS=SASL_SSL://:9092` and `KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092`:

```
############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
listeners=SASL_SSL://:9092
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
#listeners=PLAINTEXT://:9092

# Hostname and port the broker will advertise to producers and consumers. If not set,
# it uses the value for "listeners" if configured.  Otherwise, it will use the value
# returned from java.net.InetAddress.getCanonicalHostName().
advertised.listeners=SASL_SSL://:9092

# Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
```

Could you please elaborate a little more the use case when you need `listener.security.protocol.map` to be defined?

**Comment by priithaamer** [comment]
Hi, thanks for the detailed explanation. I need to override `listener.security.protocol.map` in order do define `advertised.listeners=OUTSIDE://localhost:9091,PLAINTEXT://:9092`-- different for inter-broker communication and external connections.

Anyway, i solved it with `solsson/kafka` image for now and going to close this issue.
