### ISSUE TITLE
Incorrect kafka_jaas.conf generation when PLAIN sasl mechanism is excluded

### ISSUE THREAD

**Issue by viggys** [bitnami/bitnami-docker-kafka#123]
**Description**

When `PLAIN` sasl mechanism is excluded, the `kafka_jaas.conf` is generated incorrectly. The KafkaServer PlainLoginModule listener section is missing a semi-colon at the end.
This is causing Kafka server start-up to fail.

**Steps to reproduce the issue:**

1.  `KAFKA_CFG_SASL_ENABLED_MECHANISMS='SCRAM-SHA-256,SCRAM-SHA-512'` [PLAIN is excluded]
2. `KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL='SCRAM-SHA-512'`
3.  `KAFKA_CLIENT_USERS='user'`
4.  `KAFKA_CLIENT_PASSWORDS='user-pass'`
5. `KAFKA_INTER_BROKER_USER='admin'`
6. `KAFKA_INTER_BROKER_PASSWORD='admin-pass'`

**Describe the results you received:**

Semi-colon missing after `user_admin="admin-pass"`
```
KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-pass"
   user_admin="admin-pass"
   
   org.apache.kafka.common.security.scram.ScramLoginModule required;
   };
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-pass";
   };
```

**Describe the results you expected:**

Semi-colon expected after `user_admin="admin-pass"`
```
KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-pass"
   user_admin="admin-pass";
   
   org.apache.kafka.common.security.scram.ScramLoginModule required;
   };
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-pass";
   };
```

**Additional information:**
The [libkafka.sh](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L329) script is missing the `else` block, causing the issue when `PLAIN` sasl mechanism is excluded.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

**Docker Image version**: bitnami/kafka:2.6.0-debian-10-r0 (used from [bitnami/kafka helm chart v11.8.0](https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L17))

**Comment by juan131** [comment]
Hi @viggys 

Thanks so much for reporting this issue! I was able to reproduce it.  We are currently working on a solution that will be available soon. I'll let you know as soon as it's released.

**Comment by juan131** [comment]
Hi @viggys 

Could you try with the latest changes? See https://github.com/bitnami/bitnami-docker-kafka/commit/78bc255870478d0049da51216a8a50a00b41d525

Thanks again for reporting it!

**Comment by viggys** [comment]
Hi @juan131 ,

Thank you for a quick fix. I'll try the above version and let you know.

Thanks !

**Comment by viggys** [comment]
Hi @juan131 

It's working now. Thanks again for the fix. 👍

**Comment by juan131** [comment]
Great!! I proceed to close the issue, please do not hesitate to let us know if you need something else.

**Comment by viggys** [comment]
Thanks @juan131  

Just FYI, The generated JAAS file now looks like the below,
```
KafkaServer {
   org.apache.kafka.common.security.scram.ScramLoginModule required
   username="admin"
   password="admin-pass";
   };
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-pass";
   };
```

Is `KafkaClient` jaas config not required now? For any CLI operations within the container?

**Comment by juan131** [comment]
Hi @viggys 

Do you mean sth like this?

```console
KafkaClient {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="XXXX"
    password="YYYY";
};
```

**Comment by viggys** [comment]
Hi @juan131 

Yes. Something like this. Do you think this should be included in the `kafka_jaas.conf` ?

Because, when `PLAIN` mechanism is included, similar configuration is generated with `org.apache.kafka.common.security.plain.PlainLoginModule`.

Thanks !

**Comment by juan131** [comment]
Hi @viggys 

The changes introduced in this commit should make the trick: https://github.com/bitnami/bitnami-docker-kafka/commit/a834eb565a10fa8d848d53103c273e0a0b7f9e58

Please give it a try when you have a chance.

**Comment by viggys** [comment]
Hi @juan131 ,

This should definitely work. Thanks for the above commit. ⚡ 
Much appreciated. Will try this.

Thanks 👍

**Comment by juan131** [comment]
You're welcome!
