### ISSUE TITLE
Document how to add plugins

### ISSUE THREAD

**Issue by dobesv** [bitnami/bitnami-docker-kafka#125]
**Description**

It's hard to figure out how to install plugins on top of this image, e.g. to add support for https://docs.mongodb.com/kafka-connector/current/kafka-installation/

The paths in this image are not the same as in those other docs, and there's no `plugins` folder, so some tips on how to add plugins might help people get going more quickly.

**Comment by rafariossaa** [comment]
Hi,
  In kafka you can set the plugins folder with the parameter `plugin.path`, then you will need to mount a directory in that path and put there the plugins you need.
  To set that property you will need to provide a properties file as indicated [here](https://github.com/bitnami/bitnami-docker-kafka/#user-content-full-configuration).
  Could you check if this works for you ?

**Comment by dobesv** [comment]
I'm just getting started learning kafka, so I'll have to get back to you.  Can `plugin.path` be set using an environment variable?

**Comment by miguelaeh** [comment]
Hi @dobesv ,
I am afraid there is not an env var to set the plugins. Due to the amount of configuration that Kafka allows we provide env vars for the common cases while you will need to mount a configuration file for the rest of the cases.
Regards.
