### ISSUE TITLE
Support for Keystore/Truststore type other than JKS (i.e. PKCS12)

### ISSUE THREAD

**Issue by pacer11** [bitnami/bitnami-docker-kafka#126]
FEATURE REQUEST - Question
Curious as to the reason behind support for only JKS.  Java has supported the default keystore type of PKCS12 and it would be nice to be able to use this image without having to change all of my keystores to JKS.

Please advise.

**Comment by andresbono** [comment]
Hi @pacer11, thanks for suggesting this. It seems the configuration options `ssl.truststore.type` and `ssl.keystore.type` can be used, they default to `JKS` but it can be configurable. Did you try modifying the configuration file on your own to use your PKCS12 keystore? If it works for you, it would be great if we can work together on PR addressing your feature request.
