### ISSUE TITLE
Increase message.max.bytes

### ISSUE THREAD

**Issue by gkarthiks** [bitnami/bitnami-docker-kafka#13]
To increase the message size, I couldn't find any environment variable for the kafka property `message.max.bytes`.

Am I missing something?

**Comment by javsalgar** [comment]
Is this environment variable what you are looking for?

```
KAFKA_SOCKET_REQUEST_MAX_BYTES: The maximum size of a request that the socket server will accept (protection against OOM). Default: 104857600
```

**Comment by parmenides** [comment]
I think you need to change this property **message.max.bytes** which is not accessible from ENV.

**Comment by javsalgar** [comment]
Hi,

We are just releasing version 1.1.0-6 of the container which contains the requested environment variable. It should be available in no more than two hours.

**Comment by gkarthiks** [comment]
Thanks @javsalgar 

@hwa123 can you look at the latest release?

**Comment by parmenides** [comment]
@javsalgar Thanks, I solved this by changing **message.max.bytes** in **server.properties**

**Comment by vasilypodguzov** [comment]
Dear participaints,
I have the same issue, I've tried to add in docker-compose:
KAFKA_CFG_MESSAGE_MAX_BYTES=100001200
KAFKA_MESSAGE_MAX_BYTES=100001200
But KAFKA still show the error:
"The message is 5565219 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration."
How can I increase max.request.size? Thanks!

**Comment by javsalgar** [comment]
Hi,

Looking at this

```
kafka_configure_from_environment_variables() {
    # Map environment variables to config properties
    for var in "${!KAFKA_CFG_@}"; do
        key="$(echo "$var" | sed -e 's/^KAFKA_CFG_//g' -e 's/_/\./g' | tr '[:upper:]' '[:lower:]')"
        value="${!var}"
        kafka_server_conf_set "$key" "$value"
    done
}

```

The server.properties file should contain the proper value, could you try entering the container and checking the /opt/bitnami/kafka/conf/server.properties file?

**Comment by vasilypodguzov** [comment]
Agree with you @javsalgar. I've already entered the container. But the directory /opt/bitnami/kafka/conf/ is empty. I've even tried to manually create  server.properties with next values:

`socket.request.max.bytes=104857600`
`message.max.bytes=41943040`
`max.request.size=41943040`
`replica.fetch.max.bytes=41943040`
`fetch.message.max.bytes=41943040`


and attach this file in docker-compose.yml:

`kafka-server1:`
`    image: 'bitnami/kafka:latest'`
`    networks:`
`      - kafka-net`
`    ports:`
`      - '9092:9092'`
`    environment:`
`      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181`
`      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://SERVER_IP:9092`
`      - ALLOW_PLAINTEXT_LISTENER=yes`
`      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true`
`     # - KAFKA_CFG_MESSAGE_MAX_BYTES=100001200`
`     # - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=100001200`
`      - KAFKA_SOCKET_REQUEST_MAX_BYTES=100001200`
`      - KAFKA_MESSAGE_MAX_BYTES=100001200`
`    volumes:`
`      - ./server.properties:/bitnami/kafka/config/server.properties`
`      - ./producer.properties:/bitnami/kafka/config/producer.properties`
`    depends_on:`
`      - zookeeper-server`
   
But the container goes down after the start. What I'm doing wrong?

**Comment by vasilypodguzov** [comment]
Update We've found the config files in /opt/bitnami/kafka/config. I've increased the max.request.size=100001200
message.max.bytes=100001200 and others directives in bytes in server.properties, producer.properties, consumer.properties files. I've tried to use docker-compose down and up again. But error the same.

Summary. Do I need to recreate the container and delete the docker image?

**Comment by marcosbc** [comment]
Hi @vasilypodguzov, if you mount server.properties via docker-compose it will not be set via `KAFKA_CFG_MESSAGE_MAX_BYTES`/`KAFKA_MESSAGE_MAX_BYTES`, instead you'll need modify "./server.properties" (the file you mounted) and add the property.

If you keep having issues, please share a docker-compose with the contents of mounted files, so we can help.

**Comment by vasilypodguzov** [comment]
Hi @marcosbc I've commented KAFKA_CFG_MESSAGE_MAX_BYTES/KAFKA_MESSAGE_MAX_BYTES in docker-compose.yml

I've attached my files. Thanks in advance!


[files.zip](https://github.com/bitnami/bitnami-docker-kafka/files/5757528/files.zip)

**Comment by marcosbc** [comment]
Hi @vasilypodguzov, when I run your docker-compose I can see that the config file has the correct value:

```
$ docker-compose exec kafka-server1 cat /opt/bitnami/kafka/config/server.properties | grep max
...
max.request.size=100001200
message.max.bytes=100001200
sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=
```

Can you share the exact error message? Could you also share how to reproduce the error you get on our side?

**Comment by vasilypodguzov** [comment]
Hi @marcosbc. Yes, I've also seen the correct values of the new configuration. The main issue that you can load big files ( >1MB, 5 for example). Even though we changed the value, the server still uses the old small value, which introduces the limitation.

To reproduce this issue: 

1. Try to copy any big JSON file inside your Kafka docker container by the next command:

`docker cp /home/sample.json kafka-server1:/sample.json`

2. Enter inside your Kafka container:

`docker exec -it kafka-server1 /bin/bash`

3. Create a new topic for the test:

`kafka-topics --zookeeper localhost:2181 --create --topic test_topic --partitions 1 --replication-factor 1`

4. Try to load JSON file inside test_topic:

`kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test_topic < sample.json`

You could see the next error:

**ERROR** Error when sending message to topic test_topic with key: null, value: 5565131 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.RecordTooLargeException: The message is 5565219 bytes when serialized which is larger than **1048576**, which is the value of the **max.request.size** configuration.

**Comment by marcosbc** [comment]
Hi @vasilypodguzov, I could finally reproduce your issue.

First I created a large JSON file:

```console
$ echo -n '{' > sample.json; for i in {1..1000000}; do echo -n "\"hello$i\":\"world$i\"," >> sample.json; done; echo -n '}' >> sample.json
$ ls -lah sample.json
-rw-rw-r-- 1 bitnami bitnami 27M Jan  8 13:27 sample.json
```

Then I mounted it to the Kafka container produce the message:

```
$ kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test_topic < sample.json
>[2021-01-08 12:28:34,244] ERROR Error when sending message to topic test_topic with key: null, value: 27777794 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.RecordTooLargeException: The message is 27777882 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
```

I could see that the reason it is failing is because it is not using the producer config file by default. To fix that specify the `--producer.config` flag:

```
--producer.config /opt/bitnami/kafka/config/producer.properties
```

After checking the source code of Kafka, it looks like [the configuration file is not autodetected by default](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/tools/ConsoleProducer.scala#L83) and instead you need to specify it manually each time, if you want the options to be applied. Therefore it does not look like a bug of the Bitnami Docker image for Kafka, rather it being a "feature not a bug".

**Comment by vasilypodguzov** [comment]
Dear @marcosbc , yes it really works for me. I've tried many methods until you gave me the right solution. Thanks for that! I agree with you, that it can be a "feature, not a bug". In any case, I just needed the possibility of uploading big JSONs.
Happy new year and Christmas!
