### ISSUE TITLE
Increase message.max.bytes

### ISSUE THREAD

**Issue by vasilypodguzov** [bitnami/bitnami-docker-kafka#136]
Dear participants,
I have the same issue like [this](https://github.com/bitnami/bitnami-docker-kafka/issues/13): "The message is 5565219 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration."
I've tried to add in docker-compose:

KAFKA_CFG_MESSAGE_MAX_BYTES=100001200
KAFKA_MESSAGE_MAX_BYTES=100001200

But KAFKA still shows the error. How can I increase max.request.size? Thanks!

**Comment by alemorcuq** [comment]
Hi, @vasilypodguzov.

Since you want to set `max.request.size`, you need to use the `KAFKA_CFG_MAX_REQUEST_SIZE` variable. Notice the mapping between the key and the environment variable names.

**Comment by vasilypodguzov** [comment]
Hi @alemorcuq . Just now try to do that. And set in docker-compose.yml:

      - KAFKA_SOCKET_REQUEST_MAX_BYTES=100001200
      - KAFKA_MESSAGE_MAX_BYTES=100001200
      - KAFKA_CFG_MAX_REQUEST_SIZE=100001200

I'm also used next command inside the container:

`kafka-console-producer.sh --bootstrap-server SERVER_IP:9092 --topic ICP2_input < Scenario_265.json`

But still see:

>[2020-12-31 09:57:40,041] ERROR Error when sending message to topic ICP2_input with key: null, value: 5565131 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.RecordTooLargeException: The message is 5565219 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.

**Comment by slavitch** [comment]
I have the same issue

**Comment by miguelaeh** [comment]
Hi guys, sorry we missed this issue.
@vasilypodguzov  did you re-created the configuration after changing the env variable? Be sure it is not persisted from previous runs. If it is persisted, even changing the env var will not be reflected into the config

**Comment by podguzovvasily** [comment]
Hi there. Firstly, you need to recreate the configuration. Second, if you wanna send the big JSON to the Kafka topic, you will need to use a special parameter. Try to explain what you are trying to do.
