### ISSUE TITLE
`run.sh: line 23: KAFKA_OPTS: unbound variable` with KAFKA_ZOOKEEPER_PROTOCOL=SSL

### ISSUE THREAD

**Issue by sumidiot** [bitnami/bitnami-docker-kafka#138]
**Description**

Trying to enable SSL for the image, I set KAFKA_ZOOKEEPER_PROTOCOL=SSL, and the docker fails to start, with the error: `/opt/bitnami/scripts/kafka/run.sh: line 23: KAFKA_OPTS: unbound variable`.

**Steps to reproduce the issue:**

`docker build` the following and run the resulting image:

```
FROM bitnami/kafka:2.7.0

COPY certs /bitnami/kafka/config/certs # with kafka.truststore.jks, kafka.keystore.jks, zookeeper.truststore.jks, zookeeper.keystore.jks files in it
ENV \
    KAFKA_CFG_LISTENERS=SSL://kafka:9093 \
    KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka:9093 \
    KAFKA_CERTIFICATE_PASSWORD=abcdef \
    KAFKA_LISTENERS=SSL://kafka:9093 \
    KAFKA_ADVERTISED_LISTENERS=SSL://kafka:9093 \
    KAFKA_INTER_BROKER_LISTENER_NAME=SSL \
    KAFKA_ZOOKEEPER_PROTOCOL=SSL \
    KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=abcdef \
    KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=abcdef
```

**Describe the results you received:**

Docker fails to start, presents error: `/opt/bitnami/scripts/kafka/run.sh: line 23: KAFKA_OPTS: unbound variable`

**Describe the results you expected:**

Docker would start up without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

This seems to be something you can work around if you add KAFKA_OPTS="" as another ENV line in the Dockerfile.

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.3
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue. The error appears, as you rightly said because the `KAFKA_OPTS` environment variable is empty at this point

https://github.com/bitnami/bitnami-docker-kafka/blob/680e825188c63955ab7da8665ea4b24947bf2ea6/2/debian-10/rootfs/opt/bitnami/scripts/kafka/run.sh#L23

This is something that was added [here](https://github.com/bitnami/bitnami-docker-kafka/pull/115/files#diff-a5118382a226492922fb77485e14b8e79410a2bb39da8bcfc2f89e9a50141ea6) but there is an extra step needed. There is [a function](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L92) that defines different env. variables and set a default value if needed, in this case, `KAFKA_OPTS` should use a default value (empty, but it should be defined). I am preparing a commit to add the `KAFKA_OPTS` env. variable with an empty default value in that function and also release a new image with those changes.

I'll update this thread once released.

**Comment by carrodher** [comment]
The new version was released, you can check the code in this commit (https://github.com/bitnami/bitnami-docker-kafka/commit/2066445274925c677ebad2e8b0e35ba0b32b274e). In terms of the image, you can use the following immutable tag `2.7.0-debian-10-r19` (or any of the rolling tags like `2`, `2-debian-10`, `2.7.0`, or `latest`).

```Dockerfile
FROM bitnami/kafka:2.7.0-debian-10-r19
COPY certs /bitnami/kafka/config/certs
ENV KAFKA_CFG_LISTENERS=SSL://kafka:9093 \
    KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka:9093 \
    KAFKA_CERTIFICATE_PASSWORD=abcdef \
    KAFKA_LISTENERS=SSL://kafka:9093 \
    KAFKA_ADVERTISED_LISTENERS=SSL://kafka:9093 \
    KAFKA_INTER_BROKER_LISTENER_NAME=SSL \
    KAFKA_ZOOKEEPER_PROTOCOL=SSL \
    KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=abcdef \
    KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=abcdef
```
```console
$ docker build -t carrodher/mykafka .
$ docker run carrodher/mykafka
 16:39:56.95
 16:39:56.95 Welcome to the Bitnami kafka container
 16:39:56.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 16:39:56.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 16:39:56.95
 16:39:56.95 INFO  ==> ** Starting Kafka setup **
 16:39:57.01 INFO  ==> Initializing Kafka...
 16:39:57.02 INFO  ==> No injected configuration files found, creating default config files
 16:39:57.08 INFO  ==> ** Kafka setup finished! **
 16:39:57.09 INFO  ==> ** Starting Kafka **
[2021-01-08 16:39:58,678] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-01-08 16:39:59,150] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2021-01-08 16:39:59,210] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-01-08 16:39:59,213] INFO starting (kafka.server.KafkaServer)
[2021-01-08 16:39:59,214] INFO Connecting to zookeeper on localhost:2181 (kafka.server.KafkaServer)
[2021-01-08 16:39:59,236] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2021-01-08 16:39:59,241] INFO Client environment:zookeeper.version=3.5.8-f439ca583e70862c3068a1f2a7d4d068eec33315, built on 05/04/2020 15:53 GMT (org.apache.zookeeper.ZooKeeper)
[2021-01-08 16:39:59,241] INFO Client environment:host.name=8343d01205b5 (org.apache.zookeeper.ZooKeeper)
[2021-01-08 16:39:59,241] INFO Client environment:java.version=11.0.9.1 (org.apache.zookeeper.ZooKeeper)
[2021-01-08 16:39:59,241] INFO Client environment:java.vendor=BellSoft (org.apache.zookeeper.ZooKeeper)
[2021-01-08 16:39:59,241] INFO Client environment:java.home=/opt/bitnami/java (org.apache.zookeeper.ZooKeeper)
```

Thanks again for reporting the issue!

Please, note it's possible the images take some time to be pushed to registries. Feel free to reopen the issue if you face the same problem again.

**Comment by sumidiot** [comment]
Thanks!
