### ISSUE TITLE
2.6.0 - aws cli message about it being out of beta now

### ISSUE THREAD

**Issue by amossc** [bitnami/bitnami-docker-kafka#139]
**Description**

When executing an `aws` command inside the Kafka container, the command issues a warning message like so:

```
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
```

**Steps to reproduce the issue:**

1. Start the kafka image, I use the following `docker-compose.yml` stanza:
```
  kafka:
    image: bitnami/kafka:2.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
2. Execute from the host (a Mac laptop in my case):
```
docker exec -i {kafka_docker_name} /bin/bash -c "/opt/bitnami/kafka/bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --all-groups
```
3. Watch the command output

This isn't a blocker, but it might become an issue in the future.

**Describe the results you received:**

AWS prints the message:

```
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
```

But otherwise executes the command

**Describe the results you expected:**

AWS to not print that message

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 463
  Running: 4
  Paused: 0
  Stopped: 459
 Images: 37
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.847GiB
 Name: docker-desktop
 ID: GP7U:A3IS:65OG:JBFR:WP76:EEUS:LCBW:3OT7:4YAV:4YNE:EFLM:ZGGE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 100
  Goroutines: 93
  System Time: 2021-01-11T00:23:23.43891438Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I get the same message also on our Buildkite CI/CD servers running on Linux.

**Comment by javsalgar** [comment]
Hi,

I just checked and we don't ship the `aws` binary in the container. Did you perform any modifications in the container image?

```
Status: Downloaded newer image for bitnami/kafka:2.6.0
 10:06:56.07
 10:06:56.07 Welcome to the Bitnami kafka container
 10:06:56.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 10:06:56.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 10:06:56.08

I have no name!@66f01b8b79cc:/$ aws
bash: aws: command not found
```
