### ISSUE TITLE
Kerberos support?

### ISSUE THREAD

**Issue by yuzhichang** [bitnami/bitnami-docker-kafka#140]
**Description**

Kafka [Kerberos auth](https://kafka.apache.org/documentation/#security_sasl) setup is complicated. I wish `bitnami-docker-kafka` be able to make it easier.

**Comment by carrodher** [comment]
Thanks for the suggestion! At this moment it is not something we have on our roadmap in the short term. That being said, all the Kafka initialization and configuration code are in this repository. PRs are more than welcome, we will be happy to guide and review any feature addition!
