### ISSUE TITLE
kafka.common.InconsistentClusterIdException

### ISSUE THREAD

**Issue by SKennick** [bitnami/bitnami-docker-kafka#149]
**Description**

I am receiving a kafka.common.InconsistentClusterIdException when running 'docker-compose up'. This happened specifically after starting the 'docker-compose-cluster.yml', stopping and removing those containers, then attempting to start the normal 'docker-compose.yml' file. 

**Steps to reproduce the issue:**

1. pull the github project, cd into it, and run 'docker-compose -f docker-compose-cluster.yml up -d'
2. stop the four containers, and remove them from docker. 
3. cd back into the project and run 'docker-compose up' 

**Describe the results you received:**

Zookeeper appears to start, but when Kafka tries to start I get the following error:

```
kafka.common.InconsistentClusterIdException: The Cluster ID sGPUBExeRBGle9kDfzdXQA doesn't match stored clusterId Some(PwtW_Y7kQ9GwBPSRhKfq8A) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
kafka_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:252)
kafka_1      | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
kafka_1      | 	at kafka.Kafka$.main(Kafka.scala:82)
kafka_1      | 	at kafka.Kafka.main(Kafka.scala)
```

**Version**

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
```

- Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.744GiB
Name: linuxkit-025000000001
ID: TCE2:HOKF:XHXI:VMUV:DIKC:JM5C:PQZO:OOO3:Y3PE:RWJF:CPSP:HZWG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- I am running on Docker for Mac. Mac version 10.14.6

- I have not made any changes to docker-compose.yml or docker-compose-cluster.yml.

**Comment by andresbono** [comment]
Hi @SKennick, `docker-compose-cluster.yml` was creating some container volumes that might be conflicting with the second `docker-compose up` that you are executing. Can you check if that is the case?

**Comment by SKennick** [comment]
`docker system prune -f --volumes` seems to have done the trick. Thanks for the help @andresbono. I am relatively new to docker, so I appreciate you pointing me in the right direction./

**Comment by andresbono** [comment]
That's great!! 🎉  Closing the issue as resolved.
