### ISSUE TITLE
Provide support for Kraft

### ISSUE THREAD

**Issue by MollardMichael** [bitnami/bitnami-docker-kafka#153]
**Description**

Starting from Kafka 2.8, it is possible to start kafka without Zookeeper.
Is it something that is available out of the box (Or doable with some configs) ?

If not, is it something that you want to support ? If so I would be willing to propose a patch if you could give me some tips on how you imagine it would look like in the code base.

**Comment by marcosbc** [comment]
Hi @MollardMichael, it is not something we have in our roadmap. However it sure sounds interesting.

We would be glad to accept any external contribution, there isn't any reason we are sticking to ZooKeeper apart from it being what was used before 2.8.0. So if you could provide a patch, that would be awesome.

As for the implementation, I would recommend the following:

* Define a new environment variable like `KAFKA_ENABLE_KRAFT_MODE` (to accept boolean values like `ALLOW_PLAINTEXT_LISTENER` for instance).
* Add a new docker-compose file for Kraft (i.e. `docker-compose-kraft.yml` with the related changes).
* Modify the logic in `libkafka.sh` accordingly to use ZooKeeper or Kraft mode depending on the value of `KAFKA_ENABLE_KRAFT_MODE` (via something like `is_boolean_yes`). It would mainly affect the `kafka_initialize` function.

**Comment by OneCricketeer** [comment]
I think this should be closed in favor of the discussion in #159

**Comment by carrodher** [comment]
In order to avoid mixing conversations and efforts, I am closing this ticket in favor of #159 where more info is provided. Thanks!
