### ISSUE TITLE
[FEATURE REQUEST] Reduce image size

### ISSUE THREAD

**Issue by ForsakenHarmony** [bitnami/bitnami-docker-kafka#154]
Hey, would be great if you could provide alpine images 
Seems to potentially be almost 200MB smaller

See
- https://github.com/wurstmeister/kafka-docker (seems unmaintained)
- https://hub.docker.com/r/wurstmeister/kafka/tags

**Comment by migruiz4** [comment]
Hi @ForsakenHarmony,

We use [bitnami/minideb](https://hub.docker.com/r/bitnami/minideb/tags/) as the base image for all of our catalog and at the moment we don't have plans to release them using alpine.

I don't think the difference between both images is so significant (438MB vs 585MB = 140 MB), but the main reason for the size difference is not the base image but `wurstmeister/kafka` using Java JRE while our images are including Java JDK which is slightly bigger.

That is something we are looking into and it might help reduce or equalize the size difference between both images.

**Comment by ForsakenHarmony** [comment]
Stale bot is stupid

**Comment by migruiz4** [comment]
Hi @ForsakenHarmony ,

Sorry for the stalebot ping, but we didn't receive any feedback on my previous reply.

As I mentioned, replacing the base image with alpine for Kafka and other applications in the Bitnami catalog probably won't happen in the near future, but what we could do to reduce the size of the image is replacing the Java JDK with JRE instead.

If you agree we could rename this issue and move it to `on-hold` so stalebot won't close this issue and we will update this when we make the change to Java.

**Comment by ForsakenHarmony** [comment]
Sure, go ahead

**Comment by carrodher** [comment]
I'm closing this issue since there are no plans to move the base image from [bitnami/minideb](https://github.com/bitnami/minideb) to alpine.

As part of the [VMware Application Catalog](https://tanzu.vmware.com/application-catalog), different base images can be selected, at this moment the supported distros are Debian, CentOS, PhotonOS and Ubuntu.
