### ISSUE TITLE
does it allow another machine  which in the same network with the host machine to use kafka that running the kafka in docker in the host machine?

### ISSUE THREAD

**Issue by fjyulu** [bitnami/bitnami-docker-kafka#162]
same as the title, I test it and other machine can not use the kafka that running in the docker in host machine.
below is the message
```
[2021-05-10 23:19:09,040] WARN [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```
I didn't see docs about this scene , maybe this is just a unrealistic

**Comment by marcosbc** [comment]
@fjyulu I guess what you're looking for is this: [Accessing Kafka with internal and external clients](https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients)
