### ISSUE TITLE
Auto Scale Kafka Replica Node

### ISSUE THREAD

**Issue by ranjeetranjan** [bitnami/bitnami-docker-kafka#165]
Hi,

Just wanted to know is there any setting where we can set up autoscale based on the CPU and Memory utilization inside the Kubernetes.

**Comment by rafariossaa** [comment]
Hi,
  For that you will need to create an [horizontal pod autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/). The chart does not include it.

**Comment by ranjeetranjan** [comment]
Thanks @rafariossaa for your response. 
WIll Kafka also create the topic and when a new pod is created by horizontal pod autoscaler?

**Comment by rafariossaa** [comment]
Hi @ranjeetranjan ,
  Not sure if that would work that way without handling it in the initialization logic in the container image.
