### ISSUE TITLE
Require images for ARM64

### ISSUE THREAD

**Issue by odidev** [bitnami/bitnami-docker-kafka#166]
I am trying to build bitnami-docker-kafka image over ARM64 but it seems it does not have ARM64 supported tags in the [docker hub](https://hub.docker.com/r/bitnami/kafka/tags?page=1&ordering=last_updated)  

I am unable to build the image for the ARM64 platform since it uses the following tar files which are not available for the ARM64 platform: 
https://downloads.bitnami.com/files/stacksmith/wait-for-port-1.0.0-3-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/render-template-1.0.0-3-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/kafka-2.8.0-0-linux-amd64-debian-10.tar.gz
https://downloads.bitnami.com/files/stacksmith/java-11.0.11-0-linux-amd64-debian-10.tar.gz

I was able to create the arm64 equivalent tar for render-template, wait-for-ports, and Kafka by replacing the platform-dependent executables with their equivalent arm64 dependent executables.

However, I was unable to find the source of generating the binaries and shared libraries for [java-11.0.11-0-linux-amd64-debian-10.tar.gz](https://downloads.bitnami.com/files/stacksmith/java-11.0.11-0-linux-amd64-debian-10.tar.gz)

I would be happy to help in providing the arm64 support in bitnami/kafka, but it requires the arm64 supported tar for java or the source code for generating the tar for java. May I know how we can make these tars available as per the above links for arm64.

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on the Docker hub?

If interested, I will raise a PR.

**Comment by Mauraza** [comment]
Hi @odidev,

At the moment we don't have any ARM64 image. Our roadmap includes the ARM64 images, but I can't give you an estimation. 

> May I know how the amd64 image is getting published on the Docker hub?

Do you mean this https://docs.docker.com/docker-hub/repos/?

**Comment by dswiecki** [comment]
Hi @Mauraza Do you have any plans for releasing an ARM64 image?

**Comment by carrodher** [comment]
Hi all, we created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

Please visit the above-mentioned issue to see any news (when possible) about this topic.
