### ISSUE TITLE
Setting up a Kafka Cluster on multiple host?

### ISSUE THREAD

**Issue by oguzhansrky** [bitnami/bitnami-docker-kafka#170]
Hello there,

I can proceed according to the document on 1 node and set up a cluster.

But what I want is;

Kafka containers will be deployed separately on 3 nodes.

I'm attaching a screenshot below as an example.

test1 node:
![image](https://user-images.githubusercontent.com/52497227/123549136-4e9aaa00-d770-11eb-96c4-855297598688.png)

test2 node:
![image](https://user-images.githubusercontent.com/52497227/123549143-565a4e80-d770-11eb-90db-efa72b3381a4.png)

test3 node:
![image](https://user-images.githubusercontent.com/52497227/123549151-5d815c80-d770-11eb-9dee-da19f0366a40.png)

**Comment by pablogalegoc** [comment]
Hi @oguzhansrky,

Let's see if I understood correctly. What you want to achieve is three kafka nodes running on three different machines?

**Comment by oguzhansrky** [comment]
[kafka1.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840080/kafka1.txt)
[kafka2.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840081/kafka2.txt)
[kafka3.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840082/kafka3.txt)
[zookeeper1.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840083/zookeeper1.txt)
[zookeeper2.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840084/zookeeper2.txt)
[zookeeper3.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840085/zookeeper3.txt)
[docker-compose.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6840091/docker-compose.txt)

node1 docker-compose up -d zookeper1,  docker-compose up -d kafka1
node2 docker-compose up -d zookeper2,  docker-compose up -d kafka2
node3 docker-compose up -d zookeper3,  docker-compose up -d kafka3

------------------------------------
Just do it on node1.

run the commands in order.

set up a cluster
who is the leader view him
View cluster created topic

node1;
1. docker exec --user root -it kafka1 /bin/bash
2. /opt/bitnami/kafka/bin/kafka-topics.sh --create --zookeeper 10.10.10.141:2181 --topic mytopic --partitions 3 --replication-factor 3
3. kafka-topics.sh --list --zookeeper 10.10.10.141:2181
4. /opt/bitnami/kafka/bin/kafka-topics.sh --describe --zookeeper 10.10.10.141:2181 --topic mytopic

**Comment by pablogalegoc** [comment]
Happy to hear that it is solved!
