### ISSUE TITLE
how can i run 2.8.0, i don't how to config it

### ISSUE THREAD

**Issue by yuanqingx** [bitnami/bitnami-docker-kafka#171]
i want use 2.8.0 without zk, but i don't know how to config it

please

**Comment by carrodher** [comment]
Although the new version (2.8.0) was already released, we didn't perform any modification to make it works without zookeeper, there is an internal task to investigate this scenario.

In the meantime, you can check this existing issue (https://github.com/bitnami/bitnami-docker-kafka/issues/159) where other users are providing some workarounds for this configuration.

To avoid duplicating conversations, I'm closing this issue, feel free to use the above-mentioned one. Thanks!
