### ISSUE TITLE
prometheus monitoring?

### ISSUE THREAD

**Issue by raffaelespazzoli** [bitnami/bitnami-docker-kafka#172]
how can one monitor a kafka cluster deployed with this image via prometheus?
the standard approach seems to be to install the jmx-exported jar (https://github.com/prometheus/jmx_exporter), with some kafka specific config. Does this image carry that jar? If not can it be added with necessary configuration hooks?

**Comment by alemorcuq** [comment]
You can use the [bitnami/jmx-exporter](https://github.com/bitnami/charts/tree/master/bitnami/kafka) image to expose metrics. In fact, that's what the [Bitnami Kafka chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka) does by default.
