### ISSUE TITLE
Switching from Wurstmeister images 

### ISSUE THREAD

**Issue by Iskuskov** [bitnami/bitnami-docker-kafka#175]
Hello everyone! First of all, I want to thank you for such a wonderful project!

We are planning to switch Kafka images from [`Wurstmeister`](https://github.com/wurstmeister/kafka-docker) to Bitnami. Please tell me what I need to pay attention to (volumes usage, env vars, etc)? Maybe you can share some useful resources (documents, articles, etc.).

Any help would be appreciated!

**Comment by miguelaeh** [comment]
Hi @Iskuskov ,
Sorry for the late response, we missed this ticket.
You can find most of the information on the README at this very repository. If you find any issues feel free to contact us by opening a new issue.
