### ISSUE TITLE
Docker images for bug fix releases

### ISSUE THREAD

**Issue by Iskuskov** [bitnami/bitnami-docker-kafka#176]
Are there any plans to support Kafka bug fix releases?
For example:
 - [2.7.1](https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+2.7.1)
 - [2.6.2](https://downloads.apache.org/kafka/2.6.2/RELEASE_NOTES.html)
 - ...

This issue relates to https://github.com/bitnami/bitnami-docker-kafka/issues/78

**Comment by marcosbc** [comment]
Hi @Iskuskov, thanks for reporting this! We are unfortunately not maintaining bug fix releases.

However, after discussing internally, it seems like those branches are still maintained so it would make sense to support those. I've created an internal task for adding support to them, but unfortunately I cannot provide an ETA for when that will happen.

**Comment by carrodher** [comment]
Hi all, I'm closing this issue because right now, we are maintaining up to 3 branches of Kafka (the latest ones according to semver). At this very moment, those branches are 2.8.x, 3.0.x and 3.1.x.
I hope this new decision help with the described topics.
