### ISSUE TITLE
Kubernetes deployment Issue

### ISSUE THREAD

**Issue by georgethomas08** [bitnami/bitnami-docker-kafka#179]
Hi I have used bitnami/kakfa using docker compose and everything is working fine when I deployed it in Kubernetes I'm getting error like unable to create topics. I used yaml file only not helm chart.

I have added the env variable 

- name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
please see the error below

```
(kafka.server.ZkAdminManager)
org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0.
[2021-07-28 18:29:09,508] INFO [Admin Manager on Broker 1]: Error processing create topic request CreatableTopic(name='sample', numPartitions=1, replicationFactor=1, assignments=[], configs=[])
```

**Comment by miguelaeh** [comment]
Hi @georgethomas08 ,
How many brokers did you deploy?  Are they working properly?
The replication factor is the number of copies of data over multiples brokers, and looking to the error it seems there are no brokers avaiable

**Comment by georgethomas08** [comment]
@miguelaeh  Please find the deployment yaml of kafka and zookeeper below, I would like to deploy 1 broker, I'm a novice player in kubernetes
---------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: edge-kafka
  template:
    metadata:
      labels:
        app: edge-kafka
    spec: 
      containers:  
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - name: KAFKA_CFG_LISTENERS
              value: CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: 10.101.27.24:2181
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: CLIENT
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093

----------------------------------------------------

**Comment by miguelaeh** [comment]
Hi @georgethomas08 ,
I would recommend you to use our Kafka Helm Chart wich will allow you to configure the deployment easier https://github.com/bitnami/charts/tree/master/bitnami/kafka

If you want to use your own manifests you can just try to emulate the behaviour of the [docker-compose](https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml)
