### ISSUE TITLE
Broken PEM support due to kafka_truststore_filename variable being readonly

### ISSUE THREAD

**Issue by ultrr** [bitnami/bitnami-docker-kafka#184]
When trying to start a container with KAFKA_TLS_TYPE environment variable set as 'PEM' I'm getting an error:

```
kafka 16:33:10.85 
kafka 16:33:10.86 Welcome to the Bitnami kafka container
kafka 16:33:10.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 16:33:10.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 16:33:10.87 
kafka 16:33:10.87 INFO  ==> ** Starting Kafka setup **
/opt/bitnami/scripts/libkafka.sh: line 75: kafka_truststore_filename: readonly variable
```

At the 75th line of libkafka.sh the value of readonly kafka_truststore_filename variable is tried to be changed and the script fails. Same issue gonna happen for zk_truststore_filename variable (related to KAFKA_ZOOKEEPER_TLS_TYPE environment variable) at the 87th line.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this. I am fixing it, I will come back as soon as we have a new release with this fixed.

**Comment by rafariossaa** [comment]
Hi,
  Could you check release `2.8.0-debian-10-r76 release` ?

**Comment by ultrr** [comment]
Hi, looks like everything is working, thank you!

**Comment by rafariossaa** [comment]
You are welcome
