### ISSUE TITLE
Issue in kafka when running kafka exporter for metrics

### ISSUE THREAD

**Issue by avanichy25** [bitnami/bitnami-docker-kafka#188]
**Description**

i am running kafka bitnami 2.5.0 with kafka exporter 1.2.0-debian-10-r220 bitnami but recently i am seeing issue in kafka logs with client kafkexporter as Unspported version. i tried with different combinations running kafka with version 2.5.0-debian-10-r107 and exporter as 1.2.0-debian-10-r179 as well as kafka with version 2.5.0-debian-10-r96 and exporter as 1.2.0-debian-10-r168 but issue is still persistant.

```
Error when handling request: clientId=kafka_exporter, correlationId=xxxx, api=DESCRIBE_GROUPS, version=0 body={groups=xxxx,xxx,xxx} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default groupInstanceId at version 0
```

**Describe the results you received:**

```
Error when handling request: clientId=kafka_exporter, correlationId=xxxx, api=DESCRIBE_GROUPS, version=0 body={groups=xxxx,xxx,xxx} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default groupInstanceId at version 0

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
18.09.2
```

- Output of `docker-compose version` (if applicable):

```
1.21.2
```

**Comment by carrodher** [comment]
It seems it was an issue with Kafka itself (not because of a compatibility issue between Kafka and the exporter); the issue was solved at https://github.com/apache/kafka/pull/8989, but I did brief research about when the changes were merged and the following release and I think the changes were introduced as part of the 2.6.0 version. Could you try using a more recent version of Kafka?

**Comment by avanichy25** [comment]
@carrodher i tried upgrading Kafka with 2.6.0 version and the error was gone after upgrade so seems like it is a bug in Kafka 2.5.0.

Thanks
Avani
