### ISSUE TITLE
Kafka fails to start when Zookeeper has SASL and SSL enabled.

### ISSUE THREAD

**Issue by Pakkiyarasu** [bitnami/bitnami-docker-kafka#196]
Zookeeper has SSL encryption and SASL authentication enabled. Kafka also uses SASL_SSL enabled. But while starting kafka setup, it fails while connecting to Zookeeper for creating SCRAM users. 

Kafka Log:

[38;5;6mkafka [38;5;5m16:23:59.10 [0m
[38;5;6mkafka [38;5;5m16:23:59.11 [0m[1mWelcome to the Bitnami kafka container[0m
[38;5;6mkafka [38;5;5m16:23:59.11 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-kafka[0m
[38;5;6mkafka [38;5;5m16:23:59.13 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-kafka/issues[0m
[38;5;6mkafka [38;5;5m16:23:59.13 [0m
[38;5;6mkafka [38;5;5m16:23:59.13 [0m[38;5;2mINFO [0m ==> ** Starting Kafka setup **
[38;5;6mkafka [38;5;5m16:23:59.34 [0m[38;5;5mDEBUG[0m ==> Validating settings in KAFKA_* env vars...
[38;5;6mkafka [38;5;5m16:23:59.40 [0m[38;5;2mINFO [0m ==> Initializing Kafka...
[38;5;6mkafka [38;5;5m16:23:59.42 [0m[38;5;2mINFO [0m ==> No injected configuration files found, creating default config files
[38;5;6mkafka [38;5;5m16:23:59.90 [0m[38;5;2mINFO [0m ==> Configuring Kafka for inter-broker communications with SASL_SSL authentication.
[38;5;6mkafka [38;5;5m16:24:00.02 [0m[38;5;2mINFO [0m ==> Configuring Kafka for client communications with SASL_SSL authentication.
[38;5;6mkafka [38;5;5m16:24:00.04 [0m[38;5;2mINFO [0m ==> Generating JAAS authentication file
[38;5;6mkafka [38;5;5m16:24:00.05 [0m[38;5;2mINFO [0m ==> Creating users in Zookeeper
[38;5;6mkafka [38;5;5m16:24:00.06 [0m[38;5;5mDEBUG[0m ==> Creating user admin in zookeeper
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Error while executing config command with args '--zookeeper zookeeperdev-0.zookeeperdev-headless.kafka-dev.svc.cluster.local:3181,zookeeperdev-1.zookeeperdev-headless.kafka-dev.svc.cluster.local:3181,zookeeperdev-2.zookeeperdev-headless.kafka-dev.svc.cluster.local:3181 --alter --add-config SCRAM-SHA-256=[iterations=8192,password=p0xXNWWMU5],SCRAM-SHA-512=[password=p0xXNWWMU5] --entity-type users --entity-name admin'
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:271)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:267)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:125)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1948)
	at kafka.admin.ConfigCommand$.processCommandWithZk(ConfigCommand.scala:117)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:95)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
[38;5;6mkafka [38;5;5m16:24:34.76 [0m
[38;5;6mkafka [38;5;5m16:24:34.76 [0m[1mWelcome to the Bitnami kafka container[0m
[38;5;6mkafka [38;5;5m16:24:34.77 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-kafka[0m
[38;5;6mkafka [38;5;5m16:24:34.77 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-kafka/issues[0m
[38;5;6mkafka [38;5;5m16:24:34.77 [0m
[38;5;6mkafka [38;5;5m16:24:34.78 [0m[38;5;2mINFO [0m ==> ** Starting Kafka setup **
[38;5;6mkafka [38;5;5m16:24:34.88 [0m[38;5;5mDEBUG[0m ==> Validating settings in KAFKA_* env vars...
[38;5;6mkafka [38;5;5m16:24:34.91 [0m[38;5;2mINFO [0m ==> Initializing Kafka...
[38;5;6mkafka [38;5;5m16:24:34.92 [0m[38;5;2mINFO [0m ==> No injected configuration files found, creating default config files
[38;5;6mkafka [38;5;5m16:24:35.25 [0m[38;5;2mINFO [0m ==> Configuring Kafka for inter-broker communications with SASL_SSL authentication.
[38;5;6mkafka [38;5;5m16:24:35.34 [0m[38;5;2mINFO [0m ==> Configuring Kafka for client communications with SASL_SSL authentication.
[38;5;6mkafka [38;5;5m16:24:35.36 [0m[38;5;2mINFO [0m ==> Generating JAAS authentication file
[38;5;6mkafka [38;5;5m16:24:35.38 [0m[38;5;2mINFO [0m ==> Creating users in Zookeeper
[38;5;6mkafka [38;5;5m16:24:35.38 [0m[38;5;5mDEBUG[0m ==> Creating user admin in zookeeper
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.

It looks like the following code throws error.

kafka_create_sasl_scram_zookeeper_users() {
    export KAFKA_OPTS="-Djava.security.auth.login.config=${KAFKA_CONF_DIR}/kafka_jaas.conf"
    info "Creating users in Zookeeper"
    read -r -a users <<<"$(tr ',;' ' ' <<<"${KAFKA_CLIENT_USERS}")"
    read -r -a passwords <<<"$(tr ',;' ' ' <<<"${KAFKA_CLIENT_PASSWORDS}")"
    if [[ "${KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL:-}" =~ SCRAM-SHA ]]; then
        users+=("${KAFKA_INTER_BROKER_USER}")
        passwords+=("${KAFKA_INTER_BROKER_PASSWORD}")
    fi
    for ((i = 0; i < ${#users[@]}; i++)); do
        debug "Creating user ${users[i]} in zookeeper"
        # Ref: https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_scram.html#sasl-scram-overview
        debug_execute kafka-configs.sh --zookeeper "$KAFKA_CFG_ZOOKEEPER_CONNECT" --alter --add-config "SCRAM-SHA-256=[iterations=8192,password=${passwords[i]}],SCRAM-SHA-512=[password=${passwords[i]}]" --entity-type users --entity-name "${users[i]}"
    done
}

kafka-configs.sh command expects --zk-tls-config-file parameter which is not supplied. 

I tried creating user using following command, it works fine.

kafka-configs.sh --zk-tls-config-file zk-tls-config.properties --zookeeper 0.0.0.0:3181,0.0.0.0:3181,0.0.0.0:3181 --alter --add-config SCRAM-SHA-512=[iterations=8192,password=testpassword] --entity-type users --entity-name testuser

Environment:
![image](https://user-images.githubusercontent.com/14366877/138564738-9b2f48d1-4447-46fe-9525-29d9c7f106c7.png)

![image](https://user-images.githubusercontent.com/14366877/138564742-cf88e718-a803-4033-b020-d880097c4c7f.png)

Any help would be much appreciated.

**Comment by Pakkiyarasu** [comment]
@marcosbc  Thanks for helping. Can you please guide how to build and test. I could not find documents here.

**Comment by Pakkiyarasu** [comment]
@marcosbc 
https://github.com/bitnami/bitnami-docker-kafka/pull/199

Created PR. Please review. I tested by deploying in Kubernates.

**Comment by alemorcuq** [comment]
Thanks! The next tag released should have this fix implemented.
