### ISSUE TITLE
How can I set KAFKA_LOG_RETENTION_MINUTES

### ISSUE THREAD

**Issue by Andrew32bit** [bitnami/bitnami-docker-kafka#200]
How can I set  KAFKA_LOG_RETENTION_MINUTES:5? its not working

**Comment by pablogalegoc** [comment]
Hi @Andrew32bit,

That environment variable doesn't exist. You can instead mount a configuration file in `/bitnami/kafka/config/` ([README](https://github.com/bitnami/bitnami-docker-kafka#full-configuration)) for those parameters that don't have an environment variable.
