### ISSUE TITLE
Trying to write something with Python client. Producer connects but nothing happens in Consumer...

### ISSUE THREAD

**Issue by Felix-neko** [bitnami/bitnami-docker-kafka#201]
Hi folks! I'm trying to use your docker repo to set up a developer playground to play with kafka-python.

I've modified docker-compose.yml for external connection, started it -- and trying to create a producer and a consumer in Python.

```
# start_consumer.py
from kafka import KafkaConsumer

if __name__ == "__main__":
    consumer = KafkaConsumer('sample', bootstrap_servers=['localhost:9093'])
    for message in consumer:
        print(message)
```

```
# start_producer.py
from kafka import KafkaProducer

if __name__ == "__main__":
    producer = KafkaProducer(bootstrap_servers=['localhost:9093'])
    producer.send('sample', b'Hello, World!')
    producer.send('sample', key=b'message-two', value=b'This is Kafka-Python')
```

The topic on Kafka server is created, but my Consumer does not get any messages and prints nothing. How can I fix it?

https://github.com/Felix-neko/kafka_sandbox -- here's my sandbox to reproduce this strange behaviour. Maybe I have some wrong Kafka setup?

**Comment by lambertsbennett** [comment]
I am having a similar problem with the kafka helm chart. 
My producer is sending messages that I can see using the kafka-console-consumer.sh script, but my python consumer does not seem to pick up anything.

**Comment by alvneiayu** [comment]
hi all

let me try to reproduce your problem. I will come back with some feedback as soon as possible.

Thanks a lot

Álvaro

**Comment by lambertsbennett** [comment]
Thanks Álvaro. In my case I am using the bitnami/kafka chart with default settings. My producer code is:

```python
from kafka import KafkaProducer
from json import dumps

def run():
    producer = KafkaProducer(
    bootstrap_servers=['kafka-0.kafka-headless.default.svc.cluster.local:9092'],
    value_serializer=lambda x: dumps(x).encode('utf-8')
    )

    while True:
        msg = 'Helllloooo from the other siddddeeeeee.'
        print(msg)
        data = {'message': msg}
        producer.send('test', value=data)

if __name__ == '__main__':
    run()
````

and my consumer is:

```python
from kafka import KafkaConsumer
from json import loads 


def run():
    consumer = KafkaConsumer(
        'test',
        bootstrap_servers='kafka.default.svc.cluster.local:9092',
        value_deserializer=lambda x: loads(x.decode('utf-8'))
    )

    for event in consumer:
        event_data = event.value
        print(event_data)

if __name__ == '__main__':
    run()
```

**Comment by alvneiayu** [comment]
hi all

After my investigation, I included in your docker-compose @Felix-neko the environment variable:

```
KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
```

And I used those files to test:
**Consumer**
```
from kafka import KafkaConsumer

if __name__ == "__main__":
    consumer = KafkaConsumer('sample', bootstrap_servers=['localhost:9092'],auto_offset_reset='earliest')
    for message in consumer:
        print(message)
```
**Producer**
```
import json

from kafka import KafkaProducer
import time

producer = KafkaProducer(bootstrap_servers='localhost:9092', max_request_size=1048576, compression_type=None)

for i in range(10):
    data = { 'tag ': 'blah',
        'name' : 'sam',
        'index' : i,
        'score': 
            {'row1': 100,
             'row2': 200
        }
    }   
    producer.send('sample', json.dumps(data).encode('utf-8'))
    time.sleep(10)
```

And it is working. It is so important the sleep. Removing the last sleep in the producer, I can not receive message in the consumer.

Test it and let me know.

Thanks

Álvaro

**Comment by lambertsbennett** [comment]
@alvneiayu  I realize this is now a separate issue, but when I alter the advertisedListerners field I now get 'no brokers available' errors. 

A different point altogether is that it seems kind of strange that we would need to sleep for so long between calls. Doesn't this make kafka super slow to use in any real application?  (and exclude a lot of its exciting use cases?). Is this just an effect of the python package?

**Comment by Felix-neko** [comment]
Well, it looks like start_producer script just finished before the data was actualy sent to Kafka broker (it looks like the future objects were destroyed without waiting while their underlying operation will finish).

I've slightly modified start_producer script (without any additional settings in Kafka), and now it works:

```
    producer = KafkaProducer(bootstrap_servers=['localhost:9093'])
    future = producer.send('sample', b'Hello, World!')
    result = future.get(timeout=60)
    print("Sent 1")

    future = producer.send('sample', key=b'message-two', value=b'This is Kafka-Python')
    result = future.get(timeout=60)
    print("Sent 2")
```

**Comment by alvneiayu** [comment]
hi @Felix-neko 

Happy to hear this.

About your question @lambertsbennett. I tested the scripts provided by Felix-neko (modifying the bootstrap_servers link) and including the last changes inside a client pod as the chart explains and it is working.

Thanks a lot

Álvaro

**Comment by lambertsbennett** [comment]
@alvneiayu @Felix-neko   Thanks a lot for your help. I will keep working at this!

**Comment by alvneiayu** [comment]
hi @Felix-neko 

Can I close this issue? 

@lambertsbennett feel free to open a new one and ping me. I will try to help you if you have any problem

Thanks a lot

Álvaro

**Comment by Felix-neko** [comment]
Well, and if I'll pull down the latest version of docker image now -- Kafka Producer will work even if I don't explicitly wait for result?

**Comment by alvneiayu** [comment]
hi @Felix-neko 

No no, I didn't change it anything in the container. In my opinion, this is a library limitation.  I can not reproduce the problem with the bash scripts inside the Kafka containers.

Thanks a lot

Álvaro

**Comment by Felix-neko** [comment]
Well, you may close it = )
