### ISSUE TITLE
Is there a version that doesn't use ZooKeeper?

### ISSUE THREAD

**Issue by janus1345** [bitnami/bitnami-docker-kafka#214]
**Description**

Is there a version that doesn't use ZooKeeper?

**Comment by javsalgar** [comment]
Hi,

If I'm not mistaken, our installation expect Zookeeper to be available.  Could you describe your use case?

**Comment by carrodher** [comment]
Can you take a look at this existing issue https://github.com/bitnami/bitnami-docker-kafka/issues/159? There are some discussion about this topic
