### ISSUE TITLE
Issue defining SASL callback classes

### ISSUE THREAD

**Issue by adam-long** [bitnami/bitnami-docker-kafka#225]
### Name and Version

bitnami/kafka:3.1.0

### What steps will reproduce the bug?

I'm attempting to activate OIDC support described in [KIP-768](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=186877575) (which builds directly on [KIP-255](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876))

I've added a new listener and define my SASL mechanism in my `docker-compose.yml`

```
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="SASL_PLAINTEXT:SASL_PLAINTEXT"
KAFKA_LISTENERS="SASL_PLAINTEXT://:9092"
KAFKA_ADVERTISED_LISTENERS="SASL_PLAINTEXT://kafka:9092"

KAFKA_CFG_SASL_ENABLED_MECHANISMS="OAUTHBEARER"
```

I now need to define the custom SASL callback class.  According to the Kafka docs, this is done using the configuration format as follows:

- `listener.name.<listener name>.<mechanism>.sasl.server.callback.handler.class=<class>`

So I add the following to my `docker-compose.yml`:

```
KAFKA_CFG_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
```

The specified class included by default in Kafka 3.1.0, and is specified in KIP-768.

This creates a subtle error in the `server.properties` file, however, as all the underscores are replaced with periods.  The problem is that the listener name is "SASL_PLAINTEXT", not "SASL.PLAINTEXT".  

### What is the expected behavior?

The Docker Compose variable: 

```
KAFKA_CFG_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
```

will generate the server.properties entry:

```
listener.name.sasl_plaintext.oauthbearer.sasl.server.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
```

### What do you see instead?

The Docker Compose variable: 

```
KAFKA_CFG_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
```

will generate the server.properties entry:

```
listener.name.sasl.plaintext.oauthbearer.sasl.server.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
```

### Additional information

I'm not entirely sure if this is a Bitnami or a Kafka issue.  Naming listeners with underscores is a common practice I've seen documented in many examples.  And this is a fairly unique Kafka variable, in that it basically embeds information in the variable name itself.

But this is a very subtle error that I can see other people making, especially with the built-in support for OIDC new in Kafka 3.1.0, and at the very least should include a mention in the configuration documentation.

**Comment by juan131** [comment]
Hi @adam-long 

I highly recommend you to read carefully the section below of the README.md that explains how to setup SASL authentication using this Kafka container:

- https://github.com/bitnami/bitnami-docker-kafka#security

Please note that it's also possible to use your 100% custom configuration by mounting your custom configuration file in the container as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-kafka#full-configuration

**Comment by adam-long** [comment]
Hey Juan, thanks for the reply.  

I've resolved how to setup the SASL connection, but this ticket relates to a lesson learned.  The key point is how defining a custom callback handler for a SASL connection within Docker can lead to confusion when using common naming conventions.  

For instance, even though the README section on SASL connections names the listeners "INTERNAL" and "CLIENT", it switches further down in the section to using the common "SASL_SSL" listener name.  Because of the way Kafka requires you define the custom callback handler class, there is no way to use the docker environment variables to define the necessary Kafka configuration variable, as Kafka will expect `sasl_ssl`, but the scripts will turn that into `sasl.ssl` when processing the Docker environment variables.

This was somewhat a niche use case (as I don't know how many people defined custom SASL callbacks - I imagine not many) but with Kafka 3.1, a production-ready implementation of OIDC support was included, and the way to active it (per the Kafka documentation) was to point Kafka to the new implementation callback class in exactly this manner.

I agree that mounting a `server.properties` file with the callback handler class defined would solve the problem, but when the problem first manifested it wasn't immediately obvious that was what was needed, as it was not obvious what was going wrong.  For instance, when I initially examined the generated `server.properties` file, it was very easy to miss that `.` should have been `_` in the listener name.

Additionally, when this happens, the only error message produced by Kafka is a cryptic "invalid_token" error when it attempts to process a connection from a client - it doesn't even indicate what callback class was used.  

I guess my point is that it's currently very easy to create this subtle error when using common conventions and when it manifests the root cause is not obvious.  I'm not sure it's something that could be handled in the scripts, but it might be helpful to call out in the README for the container.

**Comment by javsalgar** [comment]
Hi,

Definitely, it is a niche use case. Not sure if it would make sense to add an exception to the script to catch cases like these. 

```
LISTENER_NAME_SASL_PLAINTEXT
```

Maybe doing a fix like convert

```
listener.name.sasl.plaintext
```

to 

```
listener.name.sasl_plaintext
```

I'm not sure how many cases like these are, but that's the easiest option that comes to mind.

Thoughts?

**Comment by adam-long** [comment]
It You'd need to establish how to identify the end of a listener name, as it could have zero or more underscores.  And being that the listener name could be identical to the protocol that comes next (I think its legal to have a listener name `SASL_PLAINTEXT_OAUTHBEARER` for instance), I'm not sure its actually solvable.  I think the best route is to highlight the potential pitfall and then leave it up to the developer, having been warned, not to stumble into it.

**Comment by javsalgar** [comment]
Thanks for the input. I created a task for the engineering team. I cannot guarantee an ETA but as soon as there are news we will let you know.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that starting from this revision https://github.com/bitnami/bitnami-docker-kafka/commit/54c6830d485ea287724dfa4a5fedae9871969ab3, we added a list of exception regexps to avoid the issue mentioned here. The chart has been updated as well with the latest revision of the container. Do not hesitate to re-open the ticket in case you find any issue with this fix.
