### ISSUE TITLE
Docker image arm64

### ISSUE THREAD

**Issue by foxdalas** [bitnami/bitnami-docker-kafka#226]
### Name and Version

bitnami/kafka:3

### What is the problem this feature will solve?

Hi! I am using kafka on Amazon Graviton. I can't run this image in arm platform.

### What is the feature you are proposing to solve the problem?

Kafka on Graviton

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
