### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by mcs** [bitnami/bitnami-docker-kafka#231]
### Name and Version

bitnami / bitnami-docker-kafka:latest (bitnami-bot 3.1.0-debian-10-r34 release)

### What steps will reproduce the bug?

The documentation sometimes still refers to `KAFKA_CLIENT_USER` and `KAFKA_CLIENT_PASSWORD` although both are not used anymore in the helper scripts (replaced by `KAFKA_CLIENT_USERS` and `KAFKA_CLIENT_PASSWORDS`). This caused some headache for me until I checked the Docker helper scripts.

Pull request following soon.

### What do you see instead?

`KAFKA_CLIENT_USER` is ignored and won't lead to a matching entry in `kafka_jaas.conf`. As I didn't set `KAFKA_CLIENT_USERS`, instead of my credentials, `user` and `bitnami` were added to the JAAS configuration file.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input! Would you like to submit a PR with the documentation fix?

**Comment by mcs** [comment]
I already did 😇
