### ISSUE TITLE
How do I use this images on arm64

### ISSUE THREAD

**Issue by liuruibin** [bitnami/bitnami-docker-kafka#233]
### Name and Version

bitnami/kafka:2

### What is the problem this feature will solve?

no

### What is the feature you are proposing to solve the problem?

no

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
