### ISSUE TITLE
Error=org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the last committed offset for partition vqindex-10 could be determine

### ISSUE THREAD

**Issue by sharmavickram** [bitnami/bitnami-docker-kafka#241]
### Name and Version

 2.8.1-debian-10-r31

### What steps will reproduce the bug?

after deployment, getting this issue: Error=org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the last committed offset for partition vqindex-10 could be determine

### What do you see instead?

![image](https://user-images.githubusercontent.com/9397194/161487290-c08a80d1-51e9-4ce5-a181-04f6862b714b.png)

**Comment by carrodher** [comment]
Could you please provide more info in order to reproduce the issue on our side? How are you deploying the container?

**Comment by sharmavickram** [comment]
> Could you please provide more info in order to reproduce the issue on our side? How are you deploying the container?

I just deployed using helm chart with my storgae class "cephfs" having 2 kafka brokers, when i try to deploy my application after kafka deployment its giving same error.

**Comment by rafariossaa** [comment]
Sometimes cephfs volume provisioning is slow. Did you check if kafka is up and running ? Is there any error message in the logs of kafka  pods ?
