### ISSUE TITLE
Kafka - Installers - How to - Secure Connections (SSL/HTTPS)

### ISSUE THREAD

**Issue by dolfken** [bitnami/bitnami-docker-kafka#244]
### Name and Version

bitnami/kafka:latest

### What steps will reproduce the bug?

Hi, I use the following command to spin up a non-SSL Kafka connection with a zookeeper.
```
docker run --name zookeeper -p 2181:2181 -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
```
I use the following to create a plaintext docker connection which is accessible through PLAINTEXT connections
```
docker run --name kafka -p 9092:9092 -e KAFKA_BROKER_ID=1 -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092 -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 -e KAFKA_CFG_ZOOKEEPER_CONNECT=172.17.0.6:2181 -e ALLOW_PLAINTEXT_LISTENER=yes bitnami/kafka:latest
```
Now I want to spin up that Docker container for Kafka where an SSL connection is possible to access through clients.
But I tried almost all samples and it doesn’t work. I cannot even spin up a docker container that connects to the zookeeper and it shuts down automatically.

I was hoping someone could give me an out-of-the-box example with certificates that works. So that I can test my client connection. I want to know which parameters need exact values in order to set this up.

### What do you see instead?

I would like to have an out-of-the-box example in the documentation to spin up a zookeeper and a Kafka server which are accessible with SSL (with dummy certificates) to test if my own client has the correct values to connect to Kafka.

**Comment by dolfken** [comment]
This is not really a bug, but I didn't find an alternative location to put this, I was lead to here by following topic:
https://community.bitnami.com/t/the-docker-command-to-spin-up-a-kafka-instance-with-ssl-connection/104834

**Comment by miguelaeh** [comment]
Hi @dolfken ,

We help to solve issues and fix bugs, but we cannot provide configurations for custom scenarios.
That said, I recommend you to start with the [docker-compose](https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml) and add env vars as you need them to configure your scenario.
Also, note you are using some `127.0.0.1` in your Kafka command that could cause issues since it will listen on the container loopback address.
