### ISSUE TITLE
create topic error

### ISSUE THREAD

**Issue by ywzrb** [bitnami/bitnami-docker-kafka#245]
### Name and Version

bitnami/kafka:16.2.3

### What steps will reproduce the bug?

kafka-topics.sh --create --bootstrap-server zk-zookeeper:2181 --replication-factor 1 --partitions 1 --topic test

### What do you see instead?

Error while executing topic command : Timed out waiting for a node assignment. Call: createTopics
[2022-04-15 04:07:39,044] ERROR org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createTopics
 (kafka.admin.TopicCommand$)

### Additional information

![image](https://user-images.githubusercontent.com/51774120/163516423-768d298b-fa19-43ab-a15d-0dc1cb95ead7.png)

**Comment by javsalgar** [comment]
Hi,

Could you add more steps in order to reproduce the issue? Do you have a docker-compose or a helm values.yaml that triggers the issue?

**Comment by ywzrb** [comment]
> 你好，
> 
> 您能否添加更多步骤以重现该问题？您是否有触发问题的 docker-compose 或 helm values.yaml？
this is values.yaml,other is default
[kafka-values.txt](https://github.com/bitnami/bitnami-docker-kafka/files/8509614/kafka-values.txt)

**Comment by migruiz4** [comment]
Hi @ywzrb,

Sorry for the late response. I have tried to reproduce your case using your values and I haven't been able to reproduce your issue in a fresh install environment.

I have seen you have commented some values, like `config`, `listeners`, `advertisedListeners`, `interBrokerListenerName`, `listenerSecurityProtocolMap`. Is it possible your running Kafka is overriding some of these values?

In this topic, other Kafka users commented out that the message `Timed out waiting for a node assignment. Call: createTopics` could be related to a listeners misconfiguration: https://stackoverflow.com/questions/53586130/kafka-topic-creation-timed-out-waiting-for-a-node-assignment
