### ISSUE TITLE
how to trigger graceful shutdown?

### ISSUE THREAD

**Issue by ahu0605** [bitnami/bitnami-docker-kafka#246]
### Name and Version

bitnami / bitnami-docker-kafka

### What is the problem this feature will solve?

kafka graceful shuwdown

### What is the feature you are proposing to solve the problem?

kafka must be exec shutdwon shell , before stop,the data will be clean!

### What alternatives have you considered?

in kubernetes,can exec preStop

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami kafka container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by ahu0605** [comment]
> It seems it is not an issue related to the Bitnami kafka container image but about how the application or environment is being used/configured.
> 
> For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.
> 
> That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

I know kafka surpport shutdown.sh , but bitnami did not exec the shutdown.sh . when container shutdown,the shell will kill the application
