### ISSUE TITLE
kafka docker image can not read the env var KAFKA_CFG_HOST_NAME

### ISSUE THREAD

**Issue by 0x00-Li** [bitnami/bitnami-docker-kafka#262]
### Name and Version

bitnami/kafka:2.8.1-debian-10-r167

### What steps will reproduce the bug?

1. run image with docker
2. kafka config,set env var KAFKA_CFG_HOST_NAME={machine ip}  KAFKA_CFG_PORT=9092

### What is the expected behavior?

register ip to zookeeper, and client connect cluster 
could send/rec message
could create/del topic/partition

### What do you see instead?

register hostname to zookeeper, and client can not connect to cluster

**Comment by fmulero** [comment]
Hi @0x00-Li 

Sorry I am not sure what you mean. Could you share a docker-compose with your scenario or the logs from your container? That will help us to diagnose the issue. Thanks
