### ISSUE TITLE
Images for minor versions pre-2.8

### ISSUE THREAD

**Issue by nightswimmings** [bitnami/bitnami-docker-kafka#266]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

I am trying to find a bitnami kafka image for Kafka 2.5.1 and I realised before 2.8, all versions are only available on its  base version 2.5.0, 2.6.0, 2.7.0...e. Is this following a rationale to not publish the minor ones?

### What is the feature you are proposing to solve the problem?

Would it be possible to provide minor Kafka update versions pre 2.8?

### What alternatives have you considered?

Creating them manually, but above all, document the rationale somewhere to have a clear bitnami releasing policy

**Comment by rafariossaa** [comment]
Hi,
  We supported only one branch at the same time. It is related to the kafka versions time line. [When](https://kafka.apache.org/downloads) the 2.6.1 was released 2.7.0 was already the new major branch.
  I am sorry but it is not possible for us to create those versions.

**Comment by rafariossaa** [comment]
I will pass it for consideration to the development team. 
As general rule, we make releases of what upstream consider current stable branch(es). 
I am closing this issue.
