### ISSUE TITLE
Create topic fails

### ISSUE THREAD

**Issue by anguillanneuf** [bitnami/bitnami-docker-kafka#267]
### Name and Version

bitnami/kafka:3.2.0

### What steps will reproduce the bug?

1. Launch from GCP Marketplace. https://docs.bitnami.com/google/infrastructure/kafka/
2. SSH into VM from GCP Cloud Console.
3. Run `sudo /opt/bitnami/ctlscript.sh status` to confirm Kafka and Zooper are running.
4. Roughly follow https://docs.bitnami.com/google/infrastructure/kafka/administration/run-producer-consumer/ to create a topic but unable to do so. Similar to #245.
   Command I ran: `sudo /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server [Primary internal IP address copied from VM network details]:2181 --topic my-kafka-topic`
   I also tried `localhost:9092` as shown in the Kafka quickstart: https://kafka.apache.org/quickstart

### What is the expected behavior?

Create topic to succeed without having to alter anything in any config files. 

### What do you see instead?

```
tianzi@remote-kafka-vm:/opt/bitnami/kafka$ sudo /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:2181 --topic my-kafka-topic
Error while executing topic command : Timed out waiting for a node assignment. Call: createTopics
[2022-07-08 23:25:38,410] ERROR org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createTopics
 (kafka.admin.TopicCommand$)
```

### Additional information

I didn't change any configs and was expecting everything to just work if SSH'ed into the server. Not sure what I'm missing.

**Comment by javsalgar** [comment]
Awesome! Thank you so much
