### ISSUE TITLE
Variable KAFKA_INTER_BROKER_LISTENER_NAME does not exist

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-kafka#27]
Variable KAFKA_INTER_BROKER_LISTENER_NAME does not exist. It would be necessary to define broker.inter.listener.name

**Comment by tompizmor** [comment]
Hello @javieryanez,

We have added the KAFKA_INTER_BROKER_LISTENER_NAME env var to the Kafka image. The configuration section in the README has been also updated.

Can you pull the latest image and give it a try?

**Comment by javieryanez** [comment]
Thanks @tompizmor, works perfectly.
