### ISSUE TITLE
GC log increase container size

### ISSUE THREAD

**Issue by Zero-2** [bitnami/bitnami-docker-kafka#30]
By default the GC log is enabled and this option grow up quicly disk usage for the container.
I tried to pass the env GC_LOG_ENABLED: false , but seems to be ignored .

>  java -Xmx1024m -Xms1024m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true **-Xloggc:/opt/bitnami/kafka/bin/../logs/kafkaServer-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M** kafka.Kafka /opt/bitnami/kafka/config/server.properties

Looking inside the kafka-run-class.sh i see this code : 

`GC_FILE_SUFFIX='-gc.log'`
`GC_LOG_FILE_NAME=''`
`if [ "x$GC_LOG_ENABLED" = "xtrue" ]; then`
....
`fi`

looking int he logs fodler i can see the gc logs 

-rw-r--r-- 1 kafka kafka 883K Oct 29 15:29 kafkaServer-gc.log.0.current

How i can disable it?

Thanks

**Comment by tompizmor** [comment]
The loggc option is originally enabled here:

https://github.com/apache/kafka/blob/e9f6f2bdcef91f79d128e75e91a1184461ec3de6/bin/kafka-server-start.sh#L32

So all you have to do is pass the following env var to remove the `-loggc` parameter. 

```
EXTRA_ARGS=-name kafkaServer
```

**Comment by Zero-2** [comment]
I will try it. Thank you for the answer.

**Comment by tompizmor** [comment]
Ok! Let us know if that works for you!
I run a quick test and  worked fine for me!

**Comment by Zero-2** [comment]
Sorry for the delay.
It works, thanks.
