### ISSUE TITLE
Kafka corrupted index

### ISSUE THREAD

**Issue by Zero-2** [bitnami/bitnami-docker-kafka#34]
Hi all,
i'm running kafka ( 3 broker + 3 zookeeper) inside AKS cluster.
When i should restart kafka pods ( nodes upgrade for example ) i've some problems.
Pods take much times to restart due to this issue:

> Found a corrupted index file due to requirement failed: Corrupt index found, index file () has non-zero size but the last offset is 2076 which is no larger than the base offset 2076.}. deleting ... and rebuilding index... (kafka.log.Log)

How i can prevent this or how i can fix it?
There's a way to do a graceful shutdown?

Regards

**Comment by andresbono** [comment]
Hi @Zero-2, would you mind to join the conversation in #33 as both issues seems to be related? I'm going to close this one in favor of #33
