### ISSUE TITLE
Overriding log4j properties

### ISSUE THREAD

**Issue by momothereal** [bitnami/bitnami-docker-kafka#35]
I'm trying to override the `log4j.properties` file to enable debugging. In my docker-compose file, I added:

```yaml
volumes:
  - ./log4j.properties:/opt/bitnami/kafka/conf/log4j.properties
```

When I run the container, it exists with this error:
```
nami    INFO  Initializing kafka
kafka   INFO  ==> Validating inputs...
Error executing 'postInstallation': EBUSY: resource busy or locked, unlink '/opt/bitnami/kafka/conf/log4j.properties'
```

Is there another way to set the log4j properties?

**Comment by andresbono** [comment]
Hi @momothereal, can you try the following?

1) First create the file in your host machine:

```
touch ./log4j.properties
```

2) Mount it as a volume in `/bitnami/kafka/conf`:
```
      - ./log4j.properties:/bitnami/kafka/conf/log4j.properties
```

3) Run the container.

Let us know if it works for you.
