### ISSUE TITLE
An SSL listener is not considered 'secure' by this image

### ISSUE THREAD

**Issue by momothereal** [bitnami/bitnami-docker-kafka#36]
If I use a listener like `SSL://:9092`, the following error is thrown during startup:

```
The KAFKA_LISTENERS environment variable does not set a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is recommended only for development.
```

I would like to be able to strictly use SSL, instead of SASL_SSL or enabling PLAINTEXT listeners as the message suggests.

**Comment by loripino21** [comment]
Why did you close the issue? Did you find a solution?

**Comment by marcosbc** [comment]
Why isn't SASL_SSL valid for you? As a workaround you could do the following:

```
ALLOW_PLAINTEXT_LISTENER=yes
KAFKA_CFG_LISTENERS=SSL://:9092
KAFKA_CFG_ADVERTISED_LISTENERS=SSL://:9092
```

And then manually change configuration files as appropriate, and mount them in successive runs afterwards.

If you still think this is something we should implement let us know. But keep in mind you can also contribute this on your own via a PR by updating the [scripts responsible for the Kafka initialization logic](https://github.com/bitnami/bitnami-docker-kafka/tree/master/2/debian-9/rootfs) in all versions and platforms (if you do, mind that most of the files are identical in the different directories).
