### ISSUE TITLE
Kafka helm chart breaks when deploying with Istio

### ISSUE THREAD

**Issue by mimol91** [bitnami/bitnami-docker-kafka#38]
While deploying this chart with istio sidecar injector there is error 
`iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)` while injecting sidecar

What I understood is that this chart enable security context which cause istio to breaks

It seems that other charts have similar issue
https://github.com/istio/istio/issues/8443

Is it possible to pass argument to do not run kafka in security context?

**Comment by tompizmor** [comment]
Hi @mimol91!

Yes, in order to run the kafka and zookeeper container as root you need to install with the following options:

```
helm install --name kafkaroot --set securityContext.fsGroup=0,securityContext.runAsUser=0,zookeeper.securityContext.fsGroup=0,zookeeper.securityContext.runAsUser=0 bitnami/kafka
```

**Comment by mimol91** [comment]
Thanks @tompizmor , I could not find it in readme!
