### ISSUE TITLE
Other Kafka environment variables

### ISSUE THREAD

**Issue by justpolidor** [bitnami/bitnami-docker-kafka#41]
Is there a way to set the OFFSETS_TOPIC_REPLICATION_FACTOR and other environment variables not listed in the guide ? At the moment, if I try to set it, the image ignores the existence of that environment variable.

For example I want to set these variables
```
- name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
value: "3"
- name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
 value: "3"
- name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
value: "2"
- name: KAFKA_MIN_INSYNC_REPLICAS
value: "2"
```

When Kafka goes up, it shows the server.properties file but these values aren't in it.

**Comment by juan131** [comment]
As mentioned at https://github.com/bitnami/charts/issues/1103, the current env. variables supported are listed in the JSON file below:

https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-9/rootfs/kafka-inputs.json

As an alternative, you can avoid using the env. variables and mount your own configuration file (server.properties) as described in this [section](https://github.com/bitnami/bitnami-docker-kafka#configuration-1). For instance, on K8s you can create a configMap with your configuration and mount it at `/opt/bitnami/kafka/conf/server.properties`.

**Comment by justpolidor** [comment]
Hi @juan131 , sorry for the double issue. 
I did as you suggested, so now I mount a configMap without using the env. 
Thank you.

**Comment by juan131** [comment]
Great @justpolidor !! Please do not hesitate to let us know if you require further assistance in the future.
