### ISSUE TITLE
missing internal topics configuration override

### ISSUE THREAD

**Issue by rjanovski** [bitnami/bitnami-docker-kafka#43]
from the kafka config (server.properties):
```
############################# Internal Topic Settings  #############################
# The replication factor for the group metadata internal topics "__consumer_offsets" and "__transaction_state"
# For anything other than development testing, a value greater than 1 is recommended for to ensure availability such as 3.
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
```

so for any usage other than development, these configs need to be overwritten, but no env var to do so exists in the docker.

**Comment by tompizmor** [comment]
Hi @rjanovski,

Thanks for the feedback. I will work on adding those new environment variables to the Kafka container.
I will let you know once I made a new release.

**Comment by tompizmor** [comment]
The following environment variables are now available for the container.

- **KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:** The replication factor for the offsets topic. Default: 1
- **KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:** The replication factor for the transaction topic. Default: 1
- **KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:** Overridden min.insync.replicas config for the transaction topic. Default: 1

I will work now on updating the helm chart

**Comment by rjanovski** [comment]
thanks @tompizmor !

**Comment by tompizmor** [comment]
@rjanovski The chart has also been updated. Please test and close the issues if it works fine.

**Comment by rjanovski** [comment]
tested and looks good, thanks.

upgrade path is not smooth, however.  `helm upgrade` complaining that statefulset can only change replicas and nothing else.
maybe worth a documentation note:

**manual upgrade:**
1. `kubectl delete statefulset <release-name> --cascade=false` <- delete statefulset but keep pods
2. `helm upgrade <release-name> bitnami/kafka` <- upgrade the chart (recreate the statefulset)
3. kill pods one by one manually, for rolling update
