### ISSUE TITLE
YAML converts 'yes|no' to 'True|False'

### ISSUE THREAD

**Issue by Asgoret** [bitnami/bitnami-docker-kafka#51]
Is there any opportunity to change 'yes|no' values to 'True|False'? YAML think it's boolean and auto-change it to 'True|False' when try to deploy in OKD (Openshift).

**Comment by Asgoret** [comment]
@juan131 Hi! Can you help me little bit?)

**Comment by tompizmor** [comment]
Hi @Asgoret,

Can you let me know one of the values with that issue? We test the container and chart in several platforms and we never hit that issue.

**Comment by Asgoret** [comment]
@tompizmor in kafka it will be `ALLOW_PLAINTEXT_LISTENER`. And one moment, you need deploy it via yaml and don't put __yes__ in any screens. As workaround i use screen for values like `yes|no`.

**Comment by tompizmor** [comment]
@Asgoret It is not clear to me how you are deploying the container. 
Are you deploying a helm chart or you created manually the Kuberntes yaml files to deploy to OKD. 

Also, are you using the command line or is there any graphical interface. Sorry but I don't have much experience with Openshift

**Comment by Asgoret** [comment]
@tompizmor I create own deployment config using docker images from docker hub. There is no changes in yaml file from yours (i think).

**Comment by miguelaeh** [comment]
Could you try with [our Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka) to check if it happens too?

**Comment by Asgoret** [comment]
@miguelaeh helm charts is not recommended for use with openshift (c) Red Hat...

And i have another way of deploying process.

**Comment by tompizmor** [comment]
@Asgoret,

I don't have access to an Openshift cluster but I could try using [minishift](https://github.com/minishift/minishift). Do you know if I will be able to reproduce it that environment?

> UPD#2: If you need i can prepare depoyment config file for OKD (Openshift) 3.11 for correct reproducing

If it works for minishift it would be great.

> helm charts is not recommended for use with openshift (c) Red Hat...

I am curious about this. Did you see something like that in OpenShift documentation?

**Comment by Asgoret** [comment]
@tompizmor 

> I am curious about this. Did you see something like that in OpenShift documentation?

It was somewhere in developers blog in article about APB (Ansible Playbook Bundle).

> minishift

Yeah it will work because it's has same API, but you must use ansible k8s module for deploy. I will prepare ansible playbook in 2-3 days (need close some tasks before).

**Comment by tompizmor** [comment]
Thanks for the update. 

I'm thinking that maybe this issue doesn't have to do with the image itself but with the ansible k8s module. Did you check if there is already an open issue in their repo?

**Comment by Asgoret** [comment]
@tompizmor 
Yeah...I tried dig some information about it and open issue already (it was closed).
Some information:
1) https://github.com/ansible/ansible/issues/11905
2) https://github.com/ansible/ansible/issues/57686
3) https://stackoverflow.com/questions/47877464/how-exactly-does-ansible-parse-boolean-variables

**Comment by tompizmor** [comment]
In the first issue I see there are two possible workarounds:

1. Use `!!str` -> `!!str yes`
2. Quote the string ->  `'yes'`

Have you tried those things?
