### ISSUE TITLE
Errors when using command line instructions in readme

### ISSUE THREAD

**Issue by bbrown-extensis** [bitnami/bitnami-docker-kafka#52]
I'm using the images on dockerhub, bitnami/zookeeper:latest and bitnami/kafka:latest.

The instructions under "Using the Command Line" in your readme fail for several reasons:
1) The zookeeper bitnami image fails to start because the cfg is expected to be zoo.cfg, but is actually zookeeper.cfg.
2) The kafka bitnami image fails to start the kafka server because the server.properties file is not in the expected location. Also, I believe the environment variable KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 should be zookeeper-server:2181.

**Steps to reproduce the issue:**

1. docker pull bitnami/zookeeper:latest
2. docker network create app-tier --driver bridge
3. docker run -d --name zookeeper-server --network app-tier bitnami/zookeeper:latest
Observe: the container has exited.

After fixing zookeeper,
1. docker pull bitnami/kafka:latest
2. docker run -d --name kafka-server --network app-tier -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest
Observe: the container has exited

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true```

- Output of `docker info`:

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: XPPT:QESB:FQ5B:FMFN:MXEA:JUSB:SJ6M:GKUS:CBAZ:OO6O:VVFY:MNVG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 82
 Goroutines: 131
 System Time: 2019-06-18T21:10:42.4958267Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi, thanks for sharing this! We were able to reproduce the issues. These are the problems:

- The ZooKeeper container should set `ALLOW_ANONYMOUS_LOGIN=yes`
- The Kafka container should set `ALLOW_PLAINTEXT_LISTENER=yes`
- The Kafka container should connect to ZooKeeper via `zookeeper:2181` not `zookeeper-server:2181`

We'll work on updating these instructions.

**Comment by bbrown-extensis** [comment]
Thanks for taking a look! What you describe is a little different from what I saw, but when you have the issues resolved I will give the command line steps in the readme another try.

**Comment by marcosbc** [comment]
Hi @bbrown-extensis, it should be fixed now. Let me know if you find any issues with the commands!

**Comment by bbrown-extensis** [comment]
Looks good! The zookeeper and kafka containers stayed running. One detail though: I'm wondering if in step three, launching the client, KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 should be instead KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181.

**Comment by marcosbc** [comment]
Yes, that was fixed as well (we noticed that late). Thanks for pointing it out!
