### ISSUE TITLE
ssl.client.auth set to required even for SASL_SSL

### ISSUE THREAD

**Issue by loripino21** [bitnami/bitnami-docker-kafka#56]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

I want to setup a SASL_SSL endpoint for SASL PLAIN auth, on an encrypted SSL connection.
This is impossible to setup out of the box, as when a SASL_SSL endpoint is found ssl.client.auth is set to required by kafka_configure_sasl_ssl_listener(), so all login attemps will fail on SSL handshake

**Steps to reproduce the issue:**

1. Set KAFKA_CFG_LISTENERS="SASL_SSL://:9092" and other parameters for SASL, and provide keystore and truststore
2. all logins from all clients will fail, since they are not authenticated with a SSL client cert

**Describe the results you received:**

Client login fail

**Describe the results you expected:**

Client login success using only username and password, via SSL connection

**Additional information you deem important (e.g. issue happens only occasionally):**

-

**Version**

- Output of `docker version`:
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        774a1f4
 Built:             Sun Jun 23 06:39:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       774a1f4
  Built:            Sun Jun 23 06:38:16 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- Output of `docker info`:

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 98
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683b971d9c3ef73f284f176672c44b448662
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.14.111+
Operating System: Container-Optimized OS from Google
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.611GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://mirror.gcr.io/
Live Restore Enabled: true

- Output of `docker-compose version` (if applicable):

docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Container Optimized OS on Google CP

**Comment by marcosbc** [comment]
We have documented how to configure SSL on Kafka in the [Security section](https://github.com/bitnami/bitnami-docker-kafka#security) in the README, but I guess that's why you closed this issue.
