### ISSUE TITLE
Error while Running Docker build command from README

### ISSUE THREAD

**Issue by rcbjLevvel** [bitnami/bitnami-docker-kafka#58]
**Steps to reproduce the issue:**
I'm attempting to built the Bitnami Kafka image from scratch.

1. Open Shell on target system.
2. Run: docker build -t bitnami/kafka:latest https://github.com/bitnami/bitnami-docker-kafka.git

**Describe the results you received:**
 Command exits almost immediately with:
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git604490655/Dockerfile: no such file or directory

**Describe the results you expected:**

Bitnami Kafka image is built successfully and installed as a docker image locally.

**Additional information you deem important (e.g. issue happens only occasionally):**
OS: Linux osboxes 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 18.10

**Version**
Current github master branch.

- Output of `docker version`:

```
 docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:30:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 43
 Running: 1
 Paused: 0
 Stopped: 42
Images: 76
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-25-generic
Operating System: Ubuntu 18.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 9.586GiB
Name: osboxes
ID: FVFR:5AUU:CHEB:MFRB:FEBO:PUQ7:X5FK:IHU3:DHBA:S2QV:DXHF:NPPB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Ubuntu 18.10 Virtual Machine running on VMware Workstation Pro 15.0.2 build-10952284

**Comment by alemorcuq** [comment]
Hi, @rcbjLevvel. 

Building from a git repository allows you to specify both a commit and a build context (the directory where the `Dockerfile` is). In our repositories, `Dockerfile`s are located under `<version>/<distro>`. So, for example, in order to build Kafka 2 using Debian from `master`, you need to run:

```
$ docker build -t bitnami/kafka:latest 'https://github.com/bitnami/bitnami-docker-kafka.git#master:2/debian-9'
```

You can read more about building from a git repository in [Docker's official documentation](https://docs.docker.com/engine/reference/commandline/build/#git-repositories).

Regards,
Alejandro

**Comment by rcbjLevvel** [comment]
Thanks. I successfully built the docker image from source.

I wasn't familiar with how that aspect of docker build worked.

I will close this ticket now.
