### ISSUE TITLE
Zookeeper Failed to initialized in Kubernetes "EACCES: permission denied, open '/bitnami/zookeeper/.restored'"

### ISSUE THREAD

**Issue by amirsoleimanii** [bitnami/bitnami-docker-kafka#59]
Hello
I'm trying to run Kafka on Kubernetes, but when I run `kubernetes.yaml`, Zookeeper failed to start. These are logs from Kubernetes dashboard:

```
Welcome to the Bitnami zookeeper container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
WARN  ==> You set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing zookeeper
zookeep INFO  ==> No injected configuration files found. Creating default config file...
zookeep INFO  ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
zookeep INFO  ==> Deploying ZooKeeper with persisted data...
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/zookeeper/.restored' 
```

**Comment by juan131** [comment]
Hi @amirsoleimanii 

Did you clean the PVCs from previous deployments? It looks like you have some data from previous installations that's causing the conflict.

**Comment by amirsoleimanii** [comment]
All of my PV was Available and Released, but I delete them and again create them and it works, thank you very much.

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. We are marking this topic as “Closed".
If you have any other questions, please do not hesitate to let us know. Feel free to reopen this one if necessary.
