### ISSUE TITLE
Update to Java 11

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-kafka#66]
Currently the Kafka image is using Java 8.

According to this page: [https://kafka.apache.org/downloads](https://kafka.apache.org/downloads), since Kafka 1.0.0 Java 9 is supported, and since Kafka 2.1.0 Java 11 is supported.

When upgrading java there are important performance improvements when encryption is enabled.

**Comment by alemorcuq** [comment]
Hi, @javieryanez.

It's definitely on our roadmap. We will evaluate it and come back to you with an answer. However, I can't provide any ETA on it.

Thank you very much for your suggestion.

Regards,
Alejandro

**Comment by Mauraza** [comment]
Hi @javieryanez,

since version `2.4.0-debian-10-r22` are used Java 11. I hope that helps you.

**Comment by carrodher** [comment]
Thanks for the suggestion!

Changes were implemented in this commit https://github.com/bitnami/bitnami-docker-kafka/commit/f092cb7701a219832084cf8df9f4e4cd588eb177 for the Debian image and in this one https://github.com/bitnami/bitnami-docker-kafka/commit/469c350528ba23262a5562f4548c4971792cd707 for the Oracle one.

Please, feel free to reopen the issue if something doesn't work as expected.

**Comment by javieryanez** [comment]
Great!, As soon as I can, I'll prove it.
