### ISSUE TITLE
Support for custom users

### ISSUE THREAD

**Issue by suonto** [bitnami/bitnami-docker-kafka#70]
This is a FEATURE REQUEST. You might want to support custom users.

Currently the supported users are these:

- KAFKA_ZOOKEEPER_USER
- KAFKA_INTER_BROKER_USER
- KAFKA_BROKER_USER

However if people are using ACLs in a shared kafka cluster they probably want to add other users as well. Currently, this is only possible by overriding some of your setup at container start time.

Please add support for KAFKA_CUSTOM_USERS with some kind of user-password mapping.

**Comment by andresbono** [comment]
Hi @suonto, thanks for the suggestion. I will open an internal task to investigate it and try to schedule some time to implement it.

Feel free to start a PR if you want!

**Comment by rhysxevans** [comment]
I am looking for this functionality aswell. Please

**Comment by andresbono** [comment]
Nice, thanks for letting us know. I will add the label `on-hold` to keep the issue opened until the feature is implemented.

**Comment by suonto** [comment]
Actually, I'm not sure this is what production users would want. They probably want to use `sasl.mechanism SCRAM-SHA-...` instead of `PLAIN` because using plain would mean a broker restart on any change to users. `SCRAM` stores users in zookeeper and does not require broker restarts when modifying users. Therefore I would suggest adding `SCRAM` as an option instead of simple custom users.

More info on SCRAM here https://kafka.apache.org/documentation/#security_sasl_scram

**Comment by andresbono** [comment]
@suonto, is https://github.com/bitnami/bitnami-docker-kafka/pull/71 what you are looking for? Can you take a look and share your thoughts with us?

**Comment by rhys-evans** [comment]
Sorry, just confirming, it doesn't look like SSL auth is supported ?

**Comment by suonto** [comment]
@andresbono that is exactly what I was hoping for. I actually made the exactly same implementation today, where I just bind mounted /run.sh that used a custom (also bind mounted ) jaas config that was identical to that one in #71. My plan was to possibly open a PR later, but I'm pleasantly surprised that you guys already implemented and merged it ❤️. Would be nice to know which release it will be part though..?

Anyway, big thanks to @javieryanez (and all of you). Closing.

**Comment by andresbono** [comment]
Nice @suonto!

**Comment by andresbono** [comment]
@rhys-evans, what do you mean? Did you check this section of the [README.md: Security](https://github.com/bitnami/bitnami-docker-kafka#security)? Let us know if this is what you are looking for.

**Comment by rhys-evans** [comment]
Hi, 

Yep saw that , but essentially looking at SSL without SASL

So config would look something like (not including everything here)

```
listeners=SSL://:9093
advertised.listeners=SSL://:9093
listener.security.protocol.map=SSL:SSL
security.protocol=SSL
```

Now I may be missing something completely here, and apologise if I have.

Thanks

**Comment by andresbono** [comment]
@rhys-evans, I just opened https://github.com/bitnami/bitnami-docker-kafka/issues/74 as it seems a separate issue.
