### ISSUE TITLE
Can't set empty env variables

### ISSUE THREAD

**Issue by Millz0r** [bitnami/bitnami-docker-kafka#72]
**Description**

I was trying to set up Kafka instance with SSL, but with host verification disabled. I set the KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM env variable as empty, however that didn't work. I started debugging the issue and looking into server.properties file generated by the Docker image and it became apparent that empty env variables are not set in the config file at all. This is unfortunate, as disabling host verification requires the property to be empty.

I've noticed that the check for empty values most probably happens here:
https://github.com/bitnami/bitnami-docker-kafka/blob/4ed61f61b02624e5155256ece30237fc6b982f48/2/debian-9/rootfs/libkafka.sh#L333

**Steps to reproduce the issue:**

1. Set KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM to an empty value
2. Notice there is no entry in server.properties file
3. Set KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM to some other value
4. Notice once the value is set the server.properties file now has an entry

**Describe the results you received:**

No entry in server.properties file for empty env var.

**Describe the results you expected:**

A valid empty entry in server.properties file.

**Comment by andresbono** [comment]
Hi @Millz0r, thanks for reporting this issue. This is a caveat in the way that environment variables are handled in Bash. There is no difference between an empty value and an undefined value. So setting empty values in the configuration file is not straight-forward. We will check possible alternatives and we will get back to you.

**Comment by andresbono** [comment]
Hi @Millz0r, the latest version of the container images should have this issue fixed.
