### ISSUE TITLE
Support SSL without SASL

### ISSUE THREAD

**Issue by andresbono** [bitnami/bitnami-docker-kafka#74]
Hi, 

Yep saw that , but essentially looking at SSL without SASL

So config would look something like (not including everything here)

```
listeners=SSL://:9093
advertised.listeners=SSL://:9093
listener.security.protocol.map=SSL:SSL
security.protocol=SSL
```

Now I may be missing something completely here, and apologise if I have.

Thanks

_Originally posted by @rhys-evans in https://github.com/bitnami/bitnami-docker-kafka/issues/70#issuecomment-544843203_

**Comment by andresbono** [comment]
Ah ok, @rhys-evans. That option is not supported to be configured automatically. What you can do is mounting your own configuration file as explained here: [README.md: Full configuration](https://github.com/bitnami/bitnami-docker-kafka#full-configuration).

Please, also take a look at: https://github.com/bitnami/bitnami-docker-kafka/issues/36#issuecomment-510359919.

**Comment by rhys-evans** [comment]
Hi , thanks

I have been mounting the config for now 

Thanks

**Comment by andresbono** [comment]
Would you mind sharing the configuration that you are using with us? That way we can try to implement a way to support SSL without SASL and keep improving the container. In case you want to contribute, feel free to open a PR to update the configuration logic!
