### ISSUE TITLE
[question] Is there a way to define topics in the yml file and have them created on container creation?

### ISSUE THREAD

**Issue by whcrocker** [bitnami/bitnami-docker-kafka#75]
Perhaps using an environment variable such as: KAFKA_CREATE_TOPICS.  It would contain a comma separated list of topics.

**Comment by whcrocker** [comment]
@marcosbc - Thanks for the response.  I'm just learning kafka.  I deploy kafka in a docker environment along with producer and consumer containers.  If the consumer starts before a producer sends a message, the consumer fails with a message that the topic does not exist.  if the producer sends a message with the topic before the consumer starts, all is good.  My thought was that when the kafka container is created, a list of valid topics could be created.  Perhaps there is an init script that the container runs on startup that I missed...I will look again.  The influxdb container has a mechanism for this.  It has a script that is called on startup where it looks in a directory and runs any scripts that it finds.  This allows databases and users to be created on container creation.

**Comment by marcosbc** [comment]
Hi @whcrocker, in your case it seems like custom initialization scripts would work (i.e. what InfluxDB does).

However, it has not been implemented yet in Kafka. I've just created an internal task for that, we'll try to have it merged soon as it is a trivial change.

**Comment by marcosbc** [comment]
Hi @whcrocker, we implemented support for custom init scripts in Kafka. In order to use one, you would need to mount a .sh script inside the container's `/docker-entrypoint-initdb.d/`, which takes care of that.

Since this should allow resolving the original issue, I'm closing it. But feel free to add any comment if you think otherwise.

**Comment by whcrocker** [comment]
Awesome!  Thanks for the assistance.On Oct 31, 2019 4:30 AM, Marcos Bjoerkelund <notifications@github.com> wrote:Hi @whcrocker, we implemented support for custom init scripts in Kafka. In order to use one, you would need to mount a .sh script inside the container's /docker-entrypoint-initdb.d/, which takes care of that.
Since this should allow resolving the original issue, I'm closing it. But feel free to add any comment if you think otherwise.

**Comment by juhyxx** [comment]
I'm trying this solution but, script is runned when brokers are not available:

**Log:**
```
14:05:26.59 INFO  ==> ** Starting Kafka setup **
 14:05:26.66 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
 14:05:26.69 INFO  ==> Initializing Kafka...
 14:05:26.70 INFO  ==> No injected configuration files found, creating default config files
 14:05:26.78 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
Kafka custom init
Error while executing topic command : Replication factor: 1 larger than available brokers: 0.
[2020-03-11 14:05:48,691] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0.
 (kafka.admin.TopicCommand$)
Kafka custom init done.
 14:05:51.51 INFO  ==> ** Kafka setup finished! **

 14:05:51.54 INFO  ==> ** Starting Kafka **
```

Init sript.sh
```
echo -e "\033[1mKafka custom init\033[0m"

/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper kafka-zookeeper:2181 --create  --replication-factor 1 --partitions 2 --topic testovic
/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper kafka-zookeeper:2181 --list

echo -e "\033[1mKafka custom init done.\033[0m"
```

Did I missed something?

**Comment by marcosbc** [comment]
@juhyxx This script is executed when the initialization of each Kafka nodes is completed.

Therefore, before you run that command, you would need to check whether the brokers are available or not in the ZooKeeper instance (which has the data for the list of nodes), i.e.

```
are_brokers_available() {
    expected_num_brokers=3 # replace this with a proper value
    num_brokers=$(("$(zookeeper-shell.sh zookeeper:2181 ls /brokers/ids 2>/dev/null | grep -o , | wc -l)" + 1))
    return ((num_brokers >= expected_num_brokers))
}

while ! are_brokers_available; do
    echo "brokers not available yet"
    sleep 1
done

echo "Kafka custom init"

/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper kafka-zookeeper:2181 --create  --replication-factor 1 --partitions 2 --topic testovic
/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper kafka-zookeeper:2181 --list

echo "Kafka custom init done"
```

Alternatively, you could check for only one broker to be available if you don't know the number of expected brokers:

```
are_brokers_available() {
    zookeeper-shell.sh zookeeper:2181 ls /brokers/ids >/dev/null 2>&1
    return $?
}
```

**Comment by juhyxx** [comment]
Still now working, I checked zookeeper and it returns
```
2020-03-16 16:00:33,176 [myid:1] - WARN  [NIOWorkerThread-5:NIOServerCnxn@366] - Unable to read additional data from client sessionid 0x10001823e6c0000, likely client has closed socket
```

**Comment by marcosbc** [comment]
@juhyxx I just remembered that if you are creating the script only with the purpose of pre-defining a topic, we implemented `KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE` which will automatically create the topic when a message is sent to it. See https://github.com/bitnami/bitnami-docker-kafka/issues/11.

If that is not an option for you, you will need to start Kafka in the background, run the script and then stop Kafka. For instance, I tested the script below and it worked for me:

```
#!/bin/bash

set +x

. /libkafka.sh

# Load Kafka environment
eval "$(kafka_env)"

kafka_start_bg() {
    if [[ "${KAFKA_CFG_LISTENERS:-}" =~ SASL ]] || [[ "${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:-}" =~ SASL ]]; then
        export KAFKA_OPTS="-Djava.security.auth.login.config=$KAFKA_HOME/conf/kafka_jaas.conf"
    fi
    local flags=("$KAFKA_CONFDIR/server.properties")
    [[ -z "${KAFKA_EXTRA_FLAGS:-}" ]] || flags=("${flags[@]}" "${KAFKA_EXTRA_FLAGS[@]}")
    local start_command=("$KAFKA_HOME/bin/kafka-server-start.sh" "${flags[@]}")

    info "Starting Kafka in background"
    am_i_root && start_command=("gosu" "${KAFKA_DAEMON_USER}" "${start_command[@]}")
    if [[ "${BITNAMI_DEBUG:-false}" = true ]]; then
        "${$start_command[@]}" &
    else
        "${start_command[@]}" >/dev/null 2>&1 &
    fi
    # Wait for Kakfa to start
    local counter=0
    while (( counter < 60 )); do
        if ( cat < /dev/null > /dev/tcp/localhost/"$KAFKA_PORT_NUMBER" ) 2>/dev/null; then
            break
        fi
        echo "kafka not yet started"
        sleep 1
        ((counter++))
    done
}

kafka_stop() {
    info "Stopping Kafka"
    local stop_command=("$KAFKA_HOME/bin/kafka-server-stop.sh")
    am_i_root && stop_command=("gosu" "${KAFKA_DAEMON_USER}" "${stop_command[@]}")
    if [[ "${BITNAMI_DEBUG:-false}" = true ]]; then
        "${stop_command[@]}"
    else
        "${stop_command[@]}" >/dev/null 2>&1
    fi
}

are_brokers_available() {
    expected_num_brokers=3 # replace this with a proper value
    num_brokers=$(("$(zookeeper-shell.sh zookeeper:2181 ls /brokers/ids 2>/dev/null | grep -o , | wc -l)" + 1))
    (( num_brokers >= expected_num_brokers ))
}

echo "Kafka custom init"

kafka_start_bg

while ! are_brokers_available; do
    echo "brokers not available yet"
    sleep 1
done

# replace zookeeper:2181 with the proper host:port
/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create  --replication-factor 1 --partitions 2 --topic testovic
/opt/bitnami/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --list

kafka_stop

echo "Kafka custom init done"
```

**Comment by Miroku87** [comment]
Hi @marcosbc, I'm the same situation and I'm trying to understand: where should I put your bash script? Inside `docker-entrypoint-initdb.d`? 
And why do we need to stop kafka creating the topics?

Thank you in advance!

**Comment by marcosbc** [comment]
@Miroku87 Yes, the scripts should indeed be inside "/docker-entrypoint-initdb.d" in the container.

The reason why we need to stop Kafka is because, after the initdb scripts, the "run.sh" script is executed which starts Kafka, and if it were running it would fail.

In any case, we recommend you to take a look at the `KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE` option, it may work for your use case.

**Comment by viggys** [comment]
@marcosbc I have tried putting my init scripts inside the `/docker-entrypoint-initdb.d`. The scripts are getting executed successfully, but only during the first time the container runs.

I realised there is a [conditional check](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L626) for executing these custom init scripts.
`if [[ -n $(find "${KAFKA_INITSCRIPTS_DIR}/" -type f -regex ".*\.\(sh\)") ]] && [[ ! -f "${KAFKA_VOLUME_DIR}/.user_scripts_initialized" ]]`

I am looking for a way to execute some custom init scripts everytime the kafka container restarts.
Is there any such feature available or any workarounds that can support the above requirement?

Thanks !

**Comment by marcosbc** [comment]
@viggys For now, the easiest thing that occurs to me now is to mount a custom `entrypoint.sh` file, and configure the container to use it as `ENTRYPOINT`.

The file would look something like this:

```bash
#!/bin/bash

if [[ "$*" = "/opt/bitnami/scripts/kafka/run.sh" || "$*" = "/run.sh" ]]; then
    /opt/bitnami/scripts/kafka/setup.sh
    # Run my custom init scripts
    find /custom-init-scripts.d -type f -name '*.sh' -exec bash {} \;
fi

exec "$@"
```
