### ISSUE TITLE
Authorization/ACL

### ISSUE THREAD

**Issue by rahmnathan** [bitnami/bitnami-docker-kafka#76]
My use-case requires the ability to have per-topic Authorization. From what I can tell, the standard approach to this with kafka is via ACLs. I didn't see it mentioned anywhere in the ReadMe. I'm wondering if this is currently supported, or if it's a planned extension of this image? Thanks!

**Comment by andresbono** [comment]
Hi @rahmnathan, we setup this image with relatively basic configuration so users can customize them to suit their needs. You can use some basic environment variables listed [here](https://github.com/bitnami/bitnami-docker-kafka#configuration) but you can always mount a custom configuration file as explained here: https://github.com/bitnami/bitnami-docker-kafka#full-configuration

Does it suit your needs?

**Comment by rahmnathan** [comment]
@andresbono I'm sure we can make it work. Just making sure there isn't an abstraction available to take advantage of here. Looking at some of the other closed issues, I found the support for init scripts in '/docker-entrypoint-initdb.d'. That should allow us to do what we're looking for.

Thanks!

**Comment by rahmnathan** [comment]
One final comment - It might be worth documenting that init script information. I don't think it's currently part of the ReadMe.

**Comment by alemorcuq** [comment]
That's a good point, @rahmnathan, we should have this documented. I've created an internal task to add that bit of information to all our containers that support it. Thanks!

**Comment by israelglar** [comment]
Hey @rahmnathan just wanted to know if you managed to do it.

I'm struggling to implement it for the last 2 days but can't get it to work.

Thanks!

**Comment by rahmnathan** [comment]
@israelglar I have not started yet, but it's on my list to work on this week. I'll update here on how it goes.

**Comment by rahmnathan** [comment]
@israelglar I think I have gotten this to work (though, it's not ideal). If you have any specific questions let me know. I may post a full config here later today if I get time.

**Comment by israelglar** [comment]
@rahmnathan Hey! I ended up the docker image to `wurstmeister/kafka` because when using bitnami image I didn't found it easy to use `SCRAM-SHA-256`, change kafka's configuration, and remove the user `user` that is being used for inter-broker communication. 

I'll just leave it like this for now, but thanks anyway :)

**Comment by empikls** [comment]
@rahmnathan could you please show a config with ACLs for bitnami/kafka ?

**Comment by miguelaeh** [comment]
Hi guys, the bitnami image is supporting now all the protocols so you can take a look in case it helps

**Comment by empikls** [comment]
@miguelaeh sorry, but i can't find authorizer.class "kafka.security.auth.SimpleAclAuthorizer" in ReadMe, or it just not documented ?

**Comment by miguelaeh** [comment]
Hi @empikls ,
I was talking about this:
>  I ended up the docker image to wurstmeister/kafka because when using bitnami image I didn't found it easy to use SCRAM-SHA-256

Nevertheless, I think you can just configure the `SimpleAclAuthorizer` mounting your own `server.properties` as described here: https://github.com/bitnami/bitnami-docker-kafka#full-configuration

**Comment by ParikhKadam** [comment]
@miguelaeh @rahmnathan Can you please share an example on how to achieve this using docker and/or docker-compose?

Minimal example:
- An admin account with superuser access
- A producer who has write access to all topics
- A consumer who has read access to all topics

I did not find any ACL related configuration steps in the docs.

**Comment by miguelaeh** [comment]
Hi @ParikhKadam ,
This image has not an environment variable or any related parameter to directly configure ACLs, you need to follow the Kafka guides to configure ACLs: https://docs.confluent.io/platform/current/kafka/authorization.html
