### ISSUE TITLE
Container fails to start if ALLOW_PLAINTEXT_LISTENER is not specified

### ISSUE THREAD

**Issue by cpopp** [bitnami/bitnami-docker-kafka#77]
The container fails to start if ALLOW_PLAINTEXT_LISTENER is not specified. The documentation seems to imply this is an optional parameter that would default to no.

> $ docker run --name kafka -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest
>  18:05:13.22 
>  18:05:13.22 Welcome to the Bitnami kafka container
>  18:05:13.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
>  18:05:13.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
>  18:05:13.23 Send us your feedback at containers@bitnami.com
>  18:05:13.23 
>  18:05:13.23 INFO  ==> ** Starting Kafka setup **
> /libkafka.sh: line 212: ALLOW_PLAINTEXT_LISTENER: unbound variable

**Comment by rafariossaa** [comment]
Hi @cpopp ,
  Thanks for noticing this, we are currently working to fix it.
  Meanwhile, you to be able to start could set it manually to **no**.

  I will come back to you as soon as this is fixed.

**Comment by rafariossaa** [comment]
Hi @cpopp ,
  We have made a new release fixing this issue.
  Could you give it a try ?

Best Regards,

**Comment by cpopp** [comment]
I tested it out and the fix seems to work -- the parameter is no longer required and it defaulted to no as expected.
