### ISSUE TITLE
Kafka v2.2.2 Bitnami Docker image?

### ISSUE THREAD

**Issue by markjanstice** [bitnami/bitnami-docker-kafka#78]
Kafka v2.2.2 was released on the 1st of December, are there plans to release a Kafka v2.2.2 based Bitnami Docker image?

**Comment by jotamartos** [comment]
Hi @markjanstice ,

Thank you for your interest. We only track and release the latest version as Bitnami containers. As you can see in the Kafka's site, 2.3.1 is the latest version. 

http://kafka.apache.org/downloads.html

That's why we didn't release the version 2.2.2 in bitnami.

Regards

**Comment by markjanstice** [comment]
Hi,

Thanks for the reply. I admit 2.2.2 is an oddity given 2.2.2 was actually released 2 months after 2.3.1 i.e. there are parallel release branches with independent release schedules. People not wanting to go to 2.3.x might expect a 2.2.2 image from Bitnami but I understand if the Bitnami tooling works on the latest (numerical) version - in which case the effort may not be justified.
 
Cheers,
Mark.

**Comment by tompizmor** [comment]
Hi @markjanstice,

Do you know if the Apache Kafka project has any roadmap for the branches they maintain? If the maintain more than one branch (2.2, 2.3 and 2.4 soon ) it would make sense for us to provide more than one version as we do for other infrastructure components.

**Comment by markjanstice** [comment]
I don't have any inside information, but looking around there is evidence of parallel branch activity:

1. There is a time-based release plan https://cwiki.apache.org/confluence/display/KAFKA/Time+Based+Release+Plan which signals an intention:
> We will also attempt, as a community to do bugfix releases as needed for the last 3 releases.
2. kafka's JIRA shows bug fixing back to the 2.1 branch e.g. https://issues.apache.org/jira/browse/KAFKA-9053?jql=project%20%3D%20KAFKA%20AND%20fixVersion%20%3D%202.1.2 where they presumably will cut a 2.1.2 release at some point. 
3. Even the 1.1 branch received commits this month, that would be for a 1.1.2 https://github.com/apache/kafka/commits/1.1.

So there's lots of commit activity on lots of branches, unfortunately I have no idea when and which branches may be cut into new releases - but it can happen, the Future Release Plan seems somewhat retrospective https://cwiki.apache.org/confluence/display/KAFKA/Future+release+plan!

Cheers,
Mark.

**Comment by tompizmor** [comment]
Hi @markjanstice,

Thanks for all the info. I have created a task to start releasing more that one kafka version. However, I cannot provide you with any ETA on when this will be done.

**Comment by markjanstice** [comment]
That's good news, I wait in eager anticipation for a v2.2.2 :-)

**Comment by sameersbn** [comment]
putting this issue on-hold to block the stale bot from closing the issue

**Comment by cricket007** [comment]
Minor patches are released by Kafka/Confluent to address bugs and security patches, as needed.

AFAIK, minor releases are maintained up to 6 months apart, but that's probably a better discussion for the Kafka dev mailing lists

**Comment by nmgliangwei** [comment]
hi,Is there any progress on this issue now?

**Comment by juan131** [comment]
This is quite an old issue and I couldn't find the associated task that my colleague @tompizmor created.

Please confirm if I'm right but you're looking for us (Bitnami) to support multiple branches of Kafka (e.g `2.7` and `2.8`) instead of releasing the latest available one exclusively (`2.8.0` right now). Is that correct?

**Comment by nmgliangwei** [comment]
@juan131 Yes, I've been looking for version 2.2.2 docker image, but I can't find it.

**Comment by juan131** [comment]
Hi @nmgliangwei 

You can find every version we published in DockerHub, you just need to filter the tags, see:

- https://hub.docker.com/r/bitnami/kafka/tags?page=1&ordering=last_updated&name=2.2

That said, these old versions were built long ago (e.g. the version `2.2` was built 2 years ago) so we highly discourage using them since it's very likely to be affected by known vulnerabilities on the system libraries and other components including in the image that were patched on recent versions.

**Comment by nmgliangwei** [comment]
@juan131 
    Thank you for your reply
    Yes, I did not find a mirror image of 2.2.2 in the docker hub.
    For some special reasons, we cannot use the latest version. 
    If some versions have security problems, especially cve vulnerabilities, Kafka officials will release this fix for this version. As far as I know, bitnami has not generated docker image for this type of version. Because bitnami is only producing docker image for the latest version.
    At present, we have used version 2.3.1, which meets our requirements.
    However, it is recommended that bitnami can cover all versions of kafka.

**Comment by juan131** [comment]
Thanks for the feedback @nmgliangwei!

Please note we cannot maintain every single branch. We build/test/publish our images on a daily basis and supporting every single branch simply won't scale. That said, we always maintain the same branches the upstream project considers stable.

I was unable (checkin Apache Kafka docs) to find a site where they claim that branches prior to **2.8** are actively maintained. Could you please point me to that?

**Comment by nmgliangwei** [comment]
thank you for your reply. @juan131 

I did not find the official instructions of Kafka, but from issues.apache.org and the officially released version, if there are serious errors or CVE vulnerabilities in the previous version, the official will fix it or a patch will be submitted. Then generate a new version.

I know that bitnami cannot maintain every branch, but I still want to thank bitnami for providing us with a convenient and safe docker image.

But we can use bitnami's large version of docker image to replace the small version not provided by bitnami in the official download package. This can also be used.

This is how my zookeeper does this. I downloaded the 3.5.9 package from the zookeeper official and replaced the 3.5.7 image provided by bitnami. It can run normally. This small version upgrade almost affects the overall structure and functions of the image. Does not affect.

**Comment by juan131** [comment]
Hi @nmgliangwei 

I can provide you the instructions to modify the current [Dockerfile](https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/Dockerfile) replacing the Kafka 2.8 source tarball with the any Kafka tarball you want. Would that work for you? 

Using this way you should be able to build your custom Kafka image using 2.2.2 and the latest system packages.

**Comment by carrodher** [comment]
Hi all, I'm closing this issue because right now, we are maintaining up to 3 branches of Kafka (the latest ones according to semver). At this very moment, those branches are 2.8.x, 3.0.x and 3.1.x.
I hope this new decision help with the described topics.
