### ISSUE TITLE
Setting up a Kafka Cluster on multiple host?

### ISSUE THREAD

**Issue by ilaipi** [bitnami/bitnami-docker-kafka#80]
Can u give any suggestion about this?

thanks.

**Comment by javsalgar** [comment]
Hi,

We would need more context about what exactly you are trying to achieve. If what you want is to have a kafka cluster deployed in several nodes, that is possible. For example, if you have a Kubernetes cluster, you can use our helm chart bitnami/kafka.

https://github.com/bitnami/charts/tree/master/bitnami/kafka
