### ISSUE TITLE
SASL_PLAINTEXT producer/consumer.properties incorrectly using SASL_SSL security.protocol

### ISSUE THREAD

**Issue by antcodd** [bitnami/bitnami-docker-kafka#84]
When using ``KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://`` producer.properties/consumer.properties
is incorrectly populated with ``security.protocol=SASL_SSL`` making it difficult to use kafka tools from inside the container. This was probably a copy-paste typo.

https://github.com/bitnami/bitnami-docker-kafka/blob/6e5f33064a90e5e4b5ef11608810e94d68932c8f/2/debian-10/rootfs/libkafka.sh#L321

Should be ``SASL_PLAINTEXT``

**Comment by carrodher** [comment]
Thanks for reporting this problem and creating the associated PR, I will review the PR and close this issue once merged.
