### ISSUE TITLE
expose external port failed

### ISSUE THREAD

**Issue by taixingbi** [bitnami/bitnami-docker-kafka#88]
try implement "Setting up a Kafka Cluster" on my mac. Everything is good. But use it to test publish and receive, in external docker, got error "no broker available". means expose external port failed. how to fix?

**Comment by javsalgar** [comment]
Currently, the way that kafka works is that all nodes need to be externally accessible. Otherwise, you will not be able to access from an outside network. Could you confirm that everything works correctly if you try accessing kafka from another container inside the same network as kafka is?
