### ISSUE TITLE
[FEATURE REQUEST] Provide a local zookeeper inside the kafka container that kafka can optionally use

### ISSUE THREAD

**Issue by matthewadams** [bitnami/bitnami-docker-kafka#89]
**Description**

This is a feature request.

I'm trying to use this image in a CI/CD pipeline, and rather than trying to deal with the CI/CD provider's support (or lack thereof) for allowing CI/CD services to talk to one another, I'd rather just launch this container and tell it to start zookeeper inside the container and have kafka use that.

I suppose, for backward compatibility, the in-container zookeeper would be off by default, only activated on the presence of an environment variable.

This is nice for those use cases where we're testing and don't care at all about zookeeper.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* BitBucket CI
* GitLab CI

**Comment by matthewadams** [comment]
FYI WIP @ https://gitlab.com/northscaler-public/northscaler-docker-kafka-zookeeper

Currently getting `docker build` error below.  Any help with my image hack would be appreciated so that I can get unblocked, as this will be moot as soon as gitlab.com lands the "network-per-build" MR which is slated for 2020-03-22 or so.  That's too late for me.  🙏🏽
```
docker build -t northscaler/kafka-zookeeper .
Sending build context to Docker daemon  92.67kB
Step 1/15 : FROM bitnami/kafka:2.4.0
 ---> 09fed172522f
Step 2/15 : ENV BITNAMI_PKG_CHMOD="-R g+rwX"     HOME="/"     OS_ARCH="amd64"     OS_FLAVOUR="debian-10"     OS_NAME="linux"
 ---> Using cache
 ---> 75c855a06749
Step 3/15 : RUN install_packages ca-certificates curl libc6 procps sudo unzip zlib1g
 ---> Running in b7455de5326e
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
The command '/bin/sh -c install_packages ca-certificates curl libc6 procps sudo unzip zlib1g' returned a non-zero code: 100
```

**Comment by matthewadams** [comment]
Got something working for now:  https://hub.docker.com/repository/docker/northscaler/kafka-zookeeper

I'd prefer official support for this out of this repo.  Thanks for considering.

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR. I'm hesitant on officially creating this container as it goes against the container principle of process isolation and it would also increase the size of the final container. How difficult would it be to, instead, deploy a docker-compose so the two containers are on the same host and can talk to each other?

**Comment by matthewadams** [comment]
@javsalgar Not sure.  The use case where I'm having trouble is in a gitlab ci/cd pipeline, but the issue is temporary.  I can limp along with https://hub.docker.com/repository/docker/northscaler/kafka-zookeeper indefinitely.

**Comment by javsalgar** [comment]
Ok. If you try with a docker-compose and it works, please let us know :)

**Comment by chandanchowdhury** [comment]
@matthewadams Not sure how much this will help you, but Spotify have an old repo with exactly what you need i.e. single container running both ZooKeeper and Kafka
https://github.com/spotify/docker-kafka/

**Comment by javsalgar** [comment]
Thanks for the information @chandanchowdhury :)

**Comment by adityajalkhare** [comment]
Hi @javsalgar this might also help :

https://github.com/lensesio/fast-data-dev
