### ISSUE TITLE
Nodejs can't connect to the kafka broker in docker containers

### ISSUE THREAD

**Issue by ali-master** [bitnami/bitnami-docker-kafka#92]
**Description**
My Nodejs service can't connect to the Kafka broker in docker.
**Steps to reproduce the issue:**

1. I create a nodejs application by nestjs
2. I connect to the Kafka by nestjs microservice which is allocated into a docker container and wants to connect to the Kafka broker
3. the broker connection in the localhost(when nodejs isn't in docker) is okay but when I put the nodejs it in docker, then it can't connect to the Kafka broker.

**Describe the results you received:**
```bash
[Nest] 51   - 03/27/2020, 4:16:40 PM   [ServerKafka] ERROR [BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.18.0.4:9002 {"timestamp":"2020-03-27T16:16:40.222Z","logger":"kafkajs","retryCount":0,"retryTime":263}
```

[My docker-compose configuration file](https://gist.github.com/ali-master/252d66a13b9aa2185f2a741cede71cf6)

**Version**

- Output of `docker version`:

```
 19.03.7```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 8
  Paused: 0
  Stopped: 5
 Images: 70
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-91-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.852GiB
 Name: ubuntu-standard2-su1
 ID: 6EDX:2WBY:WY22:GT7M:AU4N:JCDM:76OH:6CVJ:MHOH:NPIT:AXMV:ORYI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
1.25.4
```

**Comment by dani8art** [comment]
Hi @ali-master did you try to connect nodejs container to the kafka one using [1]? you should take into account that inside a container kafka will not be in `localhost` but the container name if you are using `docker run` or service name if you are using `docker-compose`.


1. https://github.com/bitnami/bitnami-docker-kafka#connecting-to-other-containers

**Comment by ali-master** [comment]
Please take a look at my created docker-compose file which I added to my question. I don't know why my email-service can't see the Kafka container!

**Comment by dani8art** [comment]
are you able to find `kafka-server1` from gateway but not from email-service?

**Comment by ali-master** [comment]
Yes

**Comment by dani8art** [comment]
the only difference I can see is that `gateway` and `kafka-server1` share `internal` and `kafka` network while `email-service` and `kafka-server1` share just `kafka`. is there any impediment to also share both?

**Comment by ali-master** [comment]
I tried all networks and it doesn't work.

**Comment by dani8art** [comment]
Sorry, but I cannot reproduce the issue, this is what I did:

1. download your docker-compose file
2. `docker-compose up -d`
3.
```
$ docker-compose exec email-service bash
root@e16daa3622a3:/app# $ apt-get update && apt-get install telnet
root@e16daa3622a3:/app# $ telnet $KAFKA_HOST 9092
Trying 192.168.240.3...
Connected to kafka-server1.
Escape character is '^]'.

```

So, I would say it is not a network issue nor a configuration or Kafka issue, could you try to ensure you are setting up your email-service properly.
