### ISSUE TITLE
kafka service fails with OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000500000000, 3579117568, 0) failed; error='Not enough space' (errno=12)

### ISSUE THREAD

**Issue by javiyacollection** [bitnami/bitnami-docker-kafka#93]
Using - Docker desktop 2.2.0.3
Windows OS
------------------------------------------
This is docker-compose.yml file -
------------------------------------------
version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    ports:
      - '15182:15182'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka'
    ports:
      - '19092:19092'
    **volumes:
      - 'kafka_data:/bitnami'
    environment:
        KAFKA_CFG_ZOOKEEPER_CONNECT : zookeeper:15182
        ALLOW_PLAINTEXT_LISTENER : 'yes'
        KAFKA_HEAP_OPTS: -Xmx12G -Xms10G
        KAFKA_JVM_PERFORMANCE_OPTS: -Xmx12G -Xms10G
    depends_on:
      - zookeeper**

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
------------------------------------------------------------------------------
This is logs when it started -
-----------------------------------------------------------------------------
kafka_1      |  17:36:23.37 Welcome to the Bitnami kafka container
kafka_1      |  17:36:23.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka_1      |  17:36:23.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka_1      |  17:36:23.39 Send us your feedback at containers@bitnami.com
kafka_1      |  17:36:23.39
kafka_1      |  17:36:23.40 INFO  ==> ** Starting Kafka setup **
kafka_1      |  17:36:23.52 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka_1      |  17:36:23.73 INFO  ==> Initializing Kafka...
kafka_1      |  17:36:23.75 INFO  ==> No injected configuration files found, creating default config files
kafka_1      | find: '/docker-entrypoint-initdb.d/': No such file or directory
kafka_1      |  17:36:23.91 INFO  ==> ** Kafka setup finished! **
kafka_1      |
kafka_1      |  17:36:23.93 INFO  ==> ** Starting Kafka **
kafka_1      | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000500000000, 3579117568, 0) failed; error='Not enough space' (errno=12)
kafka_1      | #
kafka_1      | # There is insufficient memory for the Java Runtime Environment to continue.
kafka_1      | # Native memory allocation (mmap) failed to map 3579117568 bytes for committing reserved memory.
kafka_1      | # An error report file with more information is saved as:
kafka_1      | # /tmp/hs_err_pid1.log
kafka-installation_kafka_1 exited with code 1
------------------------------------------------------
when I checked container status -
-------------------------------------------------------
C:\Users\jjaviya>docker container ls -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                                                              NAMES
ff90a8373471        bitnami/kafka       "/opt/bitnami/script…"   3 minutes ago       Exited (1) 3 minutes ago                                                                      kafka-installation_kafka_1
428425c40a19        bitnami/zookeeper   "/opt/bitnami/script…"   3 minutes ago       Up 3 minutes               2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp, 0.0.0.0:15182->15182/tcp   kafka-installation_zookeeper_1

we can see here, that kafka server is stopped.

**Comment by rafariossaa** [comment]
Hi,
  Did you check how much memory is free ?
  You could do this by running:
   `dockec exec kafka-installation_zookeeper_1 free -m`

**Comment by javiyacollection** [comment]
Hi rafariossaa,

I checked free space as well,

PS C:\WINDOWS\system32> docker exec kafka-installation_zookeeper_1 free -m
              total        used        free      shared  buff/cache   available
Mem:            958         198         667          19          92         634
Swap:             0           0           0


By the way, my zookeeper worked well, kafka couldn't start and this command is not working for kafka, as this container is not in running state.


when i tried to up in debug mode, I found below logs[attached],
doubt - I am running from windows OS, why it shows with linux


[kafka startup failed.txt](https://github.com/bitnami/bitnami-docker-kafka/files/4410260/kafka.startup.failed.txt)

**Comment by rafariossaa** [comment]
Hi @javiyacollection ,
  By using these settings:
``` 
KAFKA_HEAP_OPTS: -Xmx12G -Xms10G
KAFKA_JVM_PERFORMANCE_OPTS: -Xmx12G -Xms10G
```
  you are configuring kafka to use from 10Gb to 12GB of memory, but as the `free` command reported you only have 667MB free.
 Does the machine have enough memory to run kafka with those settings ?

**Comment by javiyacollection** [comment]
Hi, 
I understood your point. 

Does the machine have enough memory to run kafka with those settings ? --> Here, which machine?
I have installed Docker desktop on my laptop (windows 10.0 OS)
How can I increase the memory of docker desktop?

and we have executed that command(docker exec kafka-installation_zookeeper_1 free -m) for particular 1 container (which is zookeeper).  this command shows the memory of overall docker machine??

**Comment by rafariossaa** [comment]
Hi,
>  --> Here, which machine?
The machine were you are running docker. Your laptop should have enough memory to run docker desktop + windows + kafka. 

> How can I increase the memory of docker desktop?
I currently don't have a windows to test this, but maybe this thread would help https://stackoverflow.com/questions/43460770/docker-windows-container-memory-limit

Could you take a look and share your findings ?

> This command shows the memory of overall docker machine??
 I could depend on the docker configuration, but usually yes.

**Comment by javiyacollection** [comment]
Thanks for the Info. I understood that run kafka server on local PC like 16GB ram is not possible.
So moving to server and over there same configuration is working.

So closing this issue.
