### ISSUE TITLE
Support custom kafka_jaas.conf

### ISSUE THREAD

**Issue by smoehrle** [bitnami/bitnami-docker-kafka#98]
**Description**

Prior to #96 it was possible to mount a custom kafka_jaas.conf with the users for SASL. Due to the fix it is no longer possible because on every startup the path provided in KAFKA_OPTS will be overwritten by the run.sh

With being forced to use the generated kafka_jaas.conf several problems arise:

1. The file generation is not really transparent and if one only sets the KAFKA_BROKER_USER it could lead to security issues due to the default user (user+bitnami) for KAFKA_INTER_BROKER_USER still being generated.

2. One is limited to a single user (with the KAFKA_INTER_BROKER_USER to two) but that is still a unnecessary limitation

**Additional information you deem important (e.g. issue happens only occasionally):**

Additional information is in the discussion of #90 . 

As a workaround I currently mount a custom run.sh with the following lines commented out.

```
if [[ "${KAFKA_CFG_LISTENERS:-}" =~ SASL ]] || [[ "${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:-}" =~ SASL ]]; then
    export KAFKA_OPTS="-Djava.security.auth.login.config=$KAFKA_CONFDIR/kafka_jaas.conf"
fi
```

**Comment by juan131** [comment]
Hi @smoehrle 

It should be possible to mount your custom `kafka_jaas.conf`. However, you need to edit the mount point as instructed in the notes below:

- https://github.com/bitnami/bitnami-docker-kafka#241-r38-debian-10

In other words, you need to use to mount the `kafka_jaas.conf` file at `/bitnami/kafka/config/kafka_jaas.conf`, instead of mounting it at `/opt//bitnami/kafka/config/kafka_jaas.conf`.

Could you please give it a try using the new mount path?

**Comment by smoehrle** [comment]
Nope, unfortunately that does not work. I just verified it to be sure, but I already tried it a few days ago because it was mentioned in the discussion in the other issue.

**Comment by juan131** [comment]
Hi @smoehrle 

I could reproduce it on my side and identify what's causing it. Thanks for reporting.

I'm working on a fix and I'll release a new version of the image asap addressing it.

**Comment by juan131** [comment]
Hi @smoehrle 

Th new version (**2.4.1-debian-10-r57**) including the fix was released. Could you please give a try? Remember to use `/bitnami/kafka/config/kafka_jaas.conf` as the mount point to include your custom Jaas configuration file.

**Comment by smoehrle** [comment]
Hey @juan131 

yes I can confirm the fix! Thanks :)
