### ISSUE TITLE
Unable to start KAFKA service when ALLOW_PLAINTEXT_LISTENER is set to no

### ISSUE THREAD

**Issue by rahulroshank** [bitnami/bitnami-docker-kafka#99]
**Description**

**Steps to reproduce the issue:**

1. Below are the contents of docker-compose file for ZOOKEEPER & KAFKA

```yaml
  zookeeper:
    image: 'bitnami/zookeeper:3.5.7'
    hostname: zookeeper
    restart: always
    container_name: zookeeper_1
    ports:
     - '2181:2181'
    expose:
     - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.4.0'
    hostname: kafka
    ports:
      - '9092:9092'
      - '9082:9082'
    expose:
      - '9092'
      - '9082'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NUM_NETWORK_THREADS=3
      - KAFKA_CFG_NUM_IO_THREADS=8
      - KAFKA_CFG_SOCKET_SE=102400
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka-logs
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=6000
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/conf/certs/server.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/conf/certs/server.truststore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=123456
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=123456
      - KAFKA_CFG_LISTENERS=SSL://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka:9092
      - KAFKA_CERTIFICATE_PASSWORD=123456
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_SSL_KEY_PASSWORD=123456
      - KAFKA_CFG_SSL_ENABLED_PROTOCOLS=TLSv1.2
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=JKS
      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=JKS
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    depends_on:
      - "zookeeper"
    volumes:
      - '/etc/kafkacert/server.keystore.jks:/opt/bitnami/kafka/conf/certs/server.keystore.jks:ro'
      - '/etc/kafkacert/server.truststore.jks:/opt/bitnami/kafka/conf/certs/server.truststore.jks:ro'
      - './Kafka/kafka-persistence:/bitnami/kafka'
```

**Describe the results you received:**

```
KAFKA logs :
08:56:18.48 Welcome to the Bitnami kafka container
 08:56:18.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 08:56:18.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 08:56:18.49 Send us your feedback at containers@bitnami.com
 08:56:18.49
 08:56:18.49 INFO  ==> ** Starting Kafka setup **
 08:56:18.54 ERROR ==> The KAFKA_CFG_LISTENERS environment variable does not configure a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
```

**Describe the results you expected:**

The Bitnami Kafka docker image disables the PLAINTEXT listener for security reasons. We can enable the PLAINTEXT listener by adding the environment variable(ALLOW_PLAINTEXT_LISTENER), but this configuration is not recommended for production.  Also, if we don't provide the parameter key(ALLOW_PLAINTEXT_LISTENER) it gives the same error message during kafka start. 

The above configuration worked fine with non-docker kafka package which was downloaded from:
http://www-us.apache.org/dist/kafka/2.2.1/kafka_2.12-2.2.1.tgz 

**Version**

- Output of `docker version`:

```
Docker version 19.03.4, build 9013bf583a
Tried with both KAFKA 2.4.0 & 2.5.0
```

- Output of `docker info`:

```
KAFKA logs :
08:56:18.48 Welcome to the Bitnami kafka container
 08:56:18.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 08:56:18.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 08:56:18.49 Send us your feedback at containers@bitnami.com
 08:56:18.49
 08:56:18.49 INFO  ==> ** Starting Kafka setup **
 08:56:18.54 ERROR ==> The KAFKA_CFG_LISTENERS environment variable does not configure a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
```

- Output of `docker-compose version` (if applicable):

```
2.0
```

**Comment by juan131** [comment]
Hi @rahulroshank 

The validations below are the ones throwing the error:

- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L221
- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L227

It seems those validations don't take into account user who configure a `SSL` listener, instead of a `SASL_SSL`. I created a PR to address this issue, thanks for reporting it!

**Comment by rahulroshank** [comment]
Which KAFKA image version will have this PR merged in? I am using image 2.4.0.

**Comment by juan131** [comment]
Hi @rahulroshank 

The changes should be available in the latest version, `2.5.0-debian-10-r9`. Could you give it a try?

**Comment by rahulroshank** [comment]
Thanks @juan131. I will test and verify the same. 
Meanwhile i have given some comments on PR-https://github.com/bitnami/bitnami-docker-kafka/pull/100. Please have a look at it.

**Comment by juan131** [comment]
HI @rahulroshank 

Could you please share the logs? By the way, you can use the latest one released today `2.5.0-debian-10-r10` (just in case).

I also answered the comments you left in the PR

**Comment by dhruvpatel29** [comment]
Hi,

I'm using kafka and zookeeper latest image. my configuration is also looking like exactly same as mention in description but still I'm getting kind of the same error.....

Also attached my docker-compose.yml file for configuration.
[docker-compose.yml.txt](https://github.com/bitnami/bitnami-docker-kafka/files/5263363/docker-compose.yml.txt)


**ERROR:** 
18:35:14.94
 18:35:14.94 Welcome to the Bitnami kafka container
 18:35:14.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 18:35:14.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 18:35:14.95
 18:35:14.95 INFO  ==> ** Starting Kafka setup **
 18:35:15.07 ERROR ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure a secure protocol. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.



Any idea on it?

**Comment by juan131** [comment]
Hi @dhruvpatel29 

The error is quite descriptive about what's happening. In your Docker Compose, you set:

```yaml
  environment:
   - ALLOW_PLAINTEXT_LISTENER=no
```

But, you didn't define the **KAFKA_ZOOKEEPER_PROTOCOL** which by default is set to `PLAINTEXT` (see https://github.com/bitnami/bitnami-docker-kafka#configuration), a non-secure protocol.

Please configure SASL authentication with Zookeeper as it's explained in the link below if you want to use "ALLOW_PLAINTEXT_LISTENER=no":

- https://github.com/bitnami/bitnami-docker-kafka#kafka-zookeeper-client-configuration

**Comment by spaceVStab** [comment]
Hi, I am facing the same issue while configuring a secured bitnami kafka stack. I am attaching the docker-compose.yml that is being used. 

```
Error:
kafka 11:20:40.28 Welcome to the Bitnami kafka container
kafka 11:20:40.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 11:20:40.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 11:20:40.30 
kafka 11:20:40.31 INFO  ==> ** Starting Kafka setup **
kafka 11:20:40.65 ERROR ==> The KAFKA_CFG_LISTENERS environment variable does not configure a secure listener. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.
```

Please help me out here.
[Uploading docker-compose-ssl-bitnami.txt…]()

**Comment by juan131** [comment]
Hi @spaceVStab 

That's very weird. You're using:

```yaml
      - KAFKA_CFG_LISTENERS=SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://10.224.93.215:9092
```

In theory, you shouldn't obtain that message since the condition below should be matched:

- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L263

Did you recently pull the Bitnami Kafka image? I just want to double-check you're using the latest changes.

**Comment by spaceVStab** [comment]
Hi, I am using this tag for bitnami kafka : bitnami/kafka:2.8.1-debian-10-r51
I got past this issue though. Figured out needed to pass `KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_FILE=/bitnami/kafka/config/certs/zookeeper.truststore.jks` as well.
Thanks !!

**Comment by juan131** [comment]
Great I'm very glad you were able to figure it out
